### ISSUE TITLE
Email template 'payment_mollie_mollie_general_second_chance_email_template' is not defined.

### ISSUE THREAD

**Issue by jellesiderius** [mollie/magento2#234] opened 2020-03-27 14:42 UTC
Hi,

After upgrading to 1.12.0, the Sales settings section in the backend throws a error. 

```Exception #0 (UnexpectedValueException): Email template 'payment_mollie_mollie_general_second_chance_email_template' is not defined.```

Is this a known issue?

**Comment by Frank-Magmodules** [comment] 2020-03-27 14:47
@jellesiderius , Thanks for opening this issue, strange, did you performed this update through Composer? And which version of Magento are you using at the moment?

**Comment by GuiltyNL** [comment] 2020-03-27 15:22
1.7.1 is the current version we are using.

Tim

**Comment by Frank-Magmodules** [comment] 2020-03-27 15:23
HI @GuiltyNL ,

Can you share your Magento 2 version number?

Frank

**Comment by GuiltyNL** [comment] 2020-03-27 15:24
2.3.3 currently. And we install via composer.

**Comment by GuiltyNL** [comment] 2020-03-27 15:34
It is trying to find:

`payment_mollie_mollie_general_second_chance_email_template`

It seems that Config.php defines a const like this:

`payment/mollie_general/second_chance_email_template`

And in the email_templates.xml it is defined like this:

`payment_other_mollie_mollie_general_second_chance_email_template`

**Comment by Frank-Magmodules** [comment] 2020-03-27 15:51
Hi @GuiltyNL  and @jellesiderius ,

Seems we can't reproduce this here on different Magento versions.
Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange log files/ login details to check and fix the issue?

**Comment by Frank-Magmodules** [comment] 2020-03-31 08:01
Hi @jellesiderius, @GuiltyNL thanks again for the detailed issue report. The issue has been resolved in the [v1.12.1](https://github.com/mollie/magento2/releases/tag/v1.12.1) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-03-31 08:01 UTC

**Comment by wezzy** [comment] 2020-05-04 20:38
Hi, I'm afraid that the bug is still there. We have Magento 2.3.3 and and Italian localization. Installing mollie-magento2 1.12.2 (a new installation, not an upgrade) we have the same problem. I've fixed it changing Config.php and adding the missing template "payment_it_mollie_mollie_general_second_chance_email_template" to the array:

`return [str_replace(
            [
                'payment_mollie_mollie_general_second_chance_email_template',
                'payment_us_mollie_mollie_general_second_chance_email_template',
                'payment_it_mollie_mollie_general_second_chance_email_template'
            ],
            'payment_other_mollie_mollie_general_second_chance_email_template',
            $templateId
        )];`

**Comment by Frank-Magmodules** [comment] 2020-05-07 09:25
Hi @wezzy, thank you for the comment. The issue has been resolved in the [v1.13.0](https://github.com/mollie/magento2/releases/tag/v1.13.0) release. We keep this issue closed for now but please feel free to reopen the issue if this still occurs.
