### ISSUE TITLE
[ISSUE] AdminHTML can't add product to admin order

### ISSUE THREAD

**Issue by riccardofinkers** [mollie/magento2#688] opened 2023-09-05 14:20 UTC
**Describe the bug**
AdminHTML can't add product to admin order

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4-p2
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.30.1

**To Reproduce**
1. Go to Sales -> Orders -> Create new order
2. After selecting customer and store view click on add products and try to add a product

**Expected behavior**
Product is added to order

**Actual behavior**
No product can be added to the order

**Actual FIX**
I have already patched this issue in file `vendor/mollie/magento2/Block/Form/Pointofsale.php` and change line 65:

````
-        } catch (\Mollie\Api\Exceptions\ApiException $exception) {
+        } catch (\Exception $exception) {
````

I have created a composer patch file for this one but it would be nice to fix this issue in the upcoming version.

**Comment by Frank-Magmodules** [comment] 2023-09-05 19:38
Hello @riccardofinkers, we appreciate your post and for sharing your potential fix. You can likely prevent this issue by manually disabling the POS method, but rest assured, we will consider your problem and potential solution for our upcoming release!

**Comment by Frank-Magmodules** [comment] 2023-09-25 12:24
Hello @riccardofinkers, we were unable to replicate this specific problem. Could you please verify if you still encounter this issue when using our [latest release](https://github.com/mollie/magento2/releases/tag/v2.31.0)?

**Comment by riccardofinkers** [comment] 2023-09-25 14:27
> Hello @riccardofinkers, we were unable to replicate this specific problem. Could you please verify if you still encounter this issue when using our [latest release](https://github.com/mollie/magento2/releases/tag/v2.31.0)?

Sorry for the late reply. I will test the newest version that came out 3 hours ago (2.31.0) because in 2.30.1 it was still present

**Comment by Frank-Magmodules** [comment] 2023-10-02 08:36
Hello @riccardofinkers, have you had the opportunity to verify whether the issue persists in the latest release?

**Comment by Frank-Magmodules** [comment] 2023-10-09 09:33
Hello @riccardofinkers, as I haven't received a response regarding this matter, I believe it can be closed. If you encounter the issue again, please don't hesitate to reopen it or create a new one.

**Comment by riccardofinkers** [comment] 2023-10-09 11:31
Sorry for the late response. 

I've updated another shop to 2.31.0  and also in this shop we can't add products in the admin on a manual order ..
![image](https://github.com/mollie/magento2/assets/34197329/826f8333-e191-417e-b346-634604b416fc)

![image](https://github.com/mollie/magento2/assets/34197329/ea05a7a5-e8e9-48a0-a727-57540cb4f8d8)

So the bug is still not fixed in 2.31.0

**Comment by Frank-Magmodules** [comment] 2023-10-09 12:05
Hello [@riccardofinkers](https://github.com/riccardofinkers), could you please provide details about the exception that’s being thrown? 
Specifically, we need the class name of the exception and its associated message. 

We are currently unable to replicate this issue, and having this information could help us identify the root cause. 
If you need help with this you can always [contact](https://www.magmodules.eu/help) us directly so we can help you out!

**Comment by Frank-Magmodules** [comment] 2023-10-24 08:26
Hello @riccardofinkers,

It appears that we have not received any further information on this ticket. Despite launching a new release of the plugin, we were unable to address your issue, as we still cannot replicate it without additional information. Could you kindly confirm if this ticket is still valid, and if it is, please reach out to us with more technical details so that we can collaborate on resolving this matter?

**Comment by Frank-Magmodules** [comment] 2023-10-30 19:49
Hi There @riccardofinkers , Because of inactivity, I am closing this matter for the time being. If you have any further questions or concerns regarding this issue, please don't hesitate to reopen this ticket or reach out to us directly.

**Closed by Frank-Magmodules** 2023-10-30 19:49 UTC
Labels: question, Investigating
