### ISSUE TITLE
Guest shopping cart not cleared completely from session after finishing order

### ISSUE THREAD

**Issue by frank-bokdam** [mollie/magento2#560] opened 2022-09-14 13:30 UTC
**Describe the bug**
After completing an order with a mollie payment method the finished quote is still present somewhere in session it seems. 
When creating a new cart after finishing the order, in cart it all seems ok. As soon as you go to checkout -> previous quote is linked again.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4
- *Open source/Enterprise/B2b*: open source
- *Mollie version number (Check configuration)*: 2.16.0

**To Reproduce**
1. Add product to cart
2. Complete order using mollie payment method
3. Create new cart with different product
4. go to checkout page

**Expected behavior**
I would expect the second product added in the quote at this point to show up in for example minicart.

**Actual behavior**
The first product that was added to quote is actually showing up in checkout and is being used from this point further to process order / payment etc.

**Additional context**
Looking at the database it looks like a new quote is actually created properly. Thus, it seems that while going to checkout page (controller) somehow the session is picking up the previous quote id again. I would assume this is not cleared properly from session. I did notice the `clearQuote()` method in magento `Success` controller is being hit.
When pushing through and creating the second order It'll also be linked to the first quote. 
After doing this a few times, it'll result in multiple orders linked to the same quote in database.

**Comment by Frank-Magmodules** [comment] 2022-09-26 06:17
HI @frank-bokdam ,

Thanks for opening this issue. After investigation with your input through Slack (wherefore thanks!), we found out that this was caused by the fact that webhooks were disabled in your (development) environment. In a regular environment, this should not happen and that’s why we are closing this issue. Feel free to reopen it if you have any questions.

**Comment by Esteraa** [comment] 2022-09-27 13:32
Hi @Frank-Magmodules Maybe we can re-open the issue as its not solved yet. I spoke with my colleague @frank-bokdam and the webhooks setting is enabled on live + the testing environment where the problem is still active. I think we still need to investigate the issue, because the problem is still there. I would be happy to help and contacted one of your colleagues through Slack also.

**Closed** 2022-10-03 19:30 UTC
Labels: Reproduced & ready for release, Investigating
