### ISSUE TITLE
Cart rules doesn't reset after cancellation

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#88] opened 2018-11-06 10:56 UTC
When an order is cancelled manually through cancel in the Magento 2 backend the salesrule_customer table is reset for example for coupons which can be used one time only, but when an order gets cancelled through a webhook call from Mollie this reset doesn't happen.

**Comment by Frank-Magmodules** [comment] 2018-11-06 13:45
HI @jorgb90, Thanks for your message on this, we were able to reproduce this in our own environment and we are getting this fixed in an upcoming release!

**Comment by jorgb90** [comment] 2018-11-07 13:15
@Frank-Magmodules Perfect! 👍

**Comment by Frank-Magmodules** [comment] 2018-11-09 13:30
Hi @jorgb90, this issue has been fixed in [v1.4.0](https://github.com/mollie/magento2/releases/tag/v1.4.0).

**Closed by Frank-Magmodules** 2018-11-09 13:30 UTC

**Comment by jorgb90** [comment] 2018-11-19 09:11
Hi @Frank-Magmodules v1.4.0 seems to not fix the issue for us, cart rules are not reset or at least not in all cases..

**Comment by Frank-Magmodules** [comment] 2018-11-19 10:21
Hi @jorgb90 ,

I can't reproduce this in our Magento 2.2.5 environment, if the payment is failed it just redirects back to the shopping-cart with the Cart Price Rule still valid. Are you using a Cart Price Rule with " Uses per Coupon/Customer" set to 1?  Please let me know how we can reproduce this.

**Comment by jorgb90** [comment] 2019-06-05 07:02
HI @Frank-Magmodules ,

Could it be possible that this logic is removed or changed in current releases? Since rules aren't reset anymore for expired or cancelled payments / orders.

**Comment by Frank-Magmodules** [comment] 2019-06-05 11:36
Hi @jorgb90 , just tried this again but can't reproduce this, can you describe the exact Steps to reproduce, pre-conditions, actual and expected result? Thanks!
