### ISSUE TITLE
No invoice is sent

### ISSUE THREAD

**Issue by downforce80** [mollie/magento2#68] opened 2018-07-11 07:35 UTC
### Preconditions
Magento 2.2.4
Mollie Version 1.3.4
Disabled amazon pay module due to this issue > https://github.com/magento/magento2/issues/14952
Extra module: Mageplaza PDF Invoice

### Steps to reproduce
Developer Mode
Add product to cart
Checkout and pay with mollie

### Expected result
Receive an email with attached invoice pdf

### Actual result
There is no invoices sent for every order which has been payed with mollie.
If we use any other payment method the invoices are attached and sent.

**Comment by Frank-Magmodules** [comment] 2018-07-11 09:48
Hi @downforce80 ,

Thanks for your clear message on this, we are going to take a look into this and we'll let you know our findings.

Frank

**Comment by Frank-Magmodules** [comment] 2018-07-13 10:21
Hi @downforce80 ,

W've jjust finished testing and it is working up to Magento 2.2.3. In 2.2.4 & 2.2.5 it is only sending out the first (order email) of the two emails, due to a newly introduced transportBuilderByStore class (which is causing some issues). See https://github.com/magento/magento2/issues/16165

This [PR 16461](https://github.com/magento/magento2/pull/16461) did fix the issue for us on 2.2.5 but please keep in mind this PR is still open.

About the other methods sending out the invoice, is this on the same time as the order email?
Let me know!

**Comment by downforce80** [comment] 2018-07-16 12:49
Hi @Frank-Magmodules 

Ok thanks i'll look into that PR. 

To answer your question, im not sure. 
For the other methods we use a module called bss autoinvoice. 
Which automatically gives a state update to any offline method from payment_review to processing.

**Comment by Marvin-Magmodules** [comment] 2018-10-04 17:58
Closing this issue now as it root cause is not within the module, but a core Magento 2 issue. As a temporary workaround, disable the Amazon Modules (if these are not used)

```bin/magento module:disable Amazon_Core Amazon_Login Amazon_Payment```

This will cause it to start working properly again.

**Closed by Marvin-Magmodules** 2018-10-04 17:58 UTC
