### ISSUE TITLE
klarna payment fee is not working 

### ISSUE THREAD

**Issue by michael-qlicks** [mollie/magento2#474] opened 2021-12-20 13:46 UTC
Klarna payment fee is not working  the line of surcharge and discount is not added to mollie_order_lines

**Used versions**
- *Magento Version number 2.4.2*:
- *Open source*:
- *Mollie version number 2.4.0*:

**To Reproduce**
1. configure poayemnt fee on klarna
2. add product to cart
3. try to submit order

disabled following plugin 
<type name="Magento\Quote\Api\CartRepositoryInterface">
       <plugin name="mollie_add_paymentfee_extension_attributes" type="Mollie\Payment\Plugin\Sales\Cart\AddPaymentFeeToCart" />
</type>

and now it works
but i clearly understand that we need this for some api export

in collect totals is setted mollie_payment_fee
in SetPaymentFeeDataOnQuote is added to extensionAttributes
in AddPaymentFeeToCart extensionAttributes are cleanned because $cart->getData('mollie_payment_fee') == 0

**Comment by Frank-Magmodules** [comment] 2021-12-21 15:09
HI @michael-qlicks ,

Thank you for opening this issue, it seems I miss some information on your ticket, between "`disabled following plugin`" and "`and now it works`". Can you add this? As I think this is an issue with a third-party plugin, right? 

As that's not clear at the moment.

**Comment by Frank-Magmodules** [comment] 2022-01-07 12:15
HI @michael-qlicks ,

Any update on my questions? 
Thanks!

**Comment by michael-qlicks** [comment] 2022-01-14 13:15
`Index: vendor/mollie/magento2/etc/di.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/mollie/magento2/etc/di.xml b/vendor/mollie/magento2/etc/di.xml
--- a/vendor/mollie/magento2/etc/di.xml
+++ b/vendor/mollie/magento2/etc/di.xml	(date 1640006341750)
@@ -73,10 +73,6 @@
         <plugin name="mollie_payment_add_subscription_data" type="Mollie\Payment\Plugin\Sales\AddRecurringData" />
     </type>

-    <type name="Magento\Quote\Api\CartRepositoryInterface">
-        <plugin name="mollie_add_paymentfee_extension_attributes" type="Mollie\Payment\Plugin\Sales\Cart\AddPaymentFeeToCart" />
-    </type>
-
     <type name="Magento\Quote\Api\Data\CartInterface">
         <plugin name="mollie_parse_metadata" type="Mollie\Payment\Plugin\Quote\Api\ParseMollieMetadata" />
     </type>`

here is the patch 
plugin was removed and it started working

**Comment by Frank-Magmodules** [comment] 2022-02-08 15:11
HI @michael-qlicks ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our <a href="https://www.magmodules.eu/support-form.html">contact form</a> so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-02-08 15:11 UTC
Labels: Investigating
