### ISSUE TITLE
items from orders with Klarna are cancelled double after expired payment

### ISSUE THREAD

**Issue by JohndeWaal** [mollie/magento2#500] opened 2022-03-16 12:25 UTC
**Describe the bug**
Items get set in stock double after the Klarna payment for an order is expired. On ordering the item is  reserved, after the payment is expired the reservation is cancelled twice.

**Used versions**

Magento Version number(eg 2.3.7)
Open source/Enterprise/B2b: Open Source
Mollie version number (Check configuration): v2.7.0 (issue already existed in v2.3.0)

**To Reproduce**
place an order with payment method Klarna pay later
Let the payment expire (on test modus choose expire from the options)
in Magento admin wait for the status to change or fetch the status from the order
check the item stock, Salable quantity is to high

**Expected behavior**
After expiration from the payment the (salable) stock should be correct, cancellation of the reservation is only once. 

**Actual behavior**
The cancellation of the stock reservation is entered twice, because of this the salable stock is to high.

Excample from my database, table stock reservation

**![screenshot](https://user-images.githubusercontent.com/5202938/158589278-c9d56ea9-7d9c-46ef-92b4-70f13a10d065.jpg)**

**Comment by Frank-Magmodules** [comment] 2022-03-21 09:21
HI @JohndeWaal ,

Thank you for opening this issue. It seems that we can't reproduce this issue from our side, can you please fill in our [support form](https://www.magmodules.eu/support-form.html) with (preferably staging/development) details of the environment so we can take a look with you on this issue?

**Comment by Frank-Magmodules** [comment] 2022-03-30 07:30
HI @JohndeWaal , 

After our direct contact, we've found out that this issue is caused by an external plugin instead of the Mollie Payment plugin, therefore, we are closing this issue for now. In case of further questions, please contact us directly through e-mail.

**Closed by Frank-Magmodules** 2022-03-30 07:30 UTC
Labels: Investigating

**Comment by Frank-Magmodules** [comment] 2023-01-05 13:22
HI @gjportegies , i needed to check out our archive but for @JohndeWaal , the issue was caused by these 2 plugins;

`Webkul_Odoomagentoconnect`  
`Webkul_Odoomagentomultishop`  
  
But unfortunately, I never had more information about how to fix this issue, sorry.

**Comment by DarekTw** [comment] 2023-01-08 21:54
Hi @Frank-Magmodules , @gjportegies 
I also have the same problem.
At the moment I have managed to establish that there are 2 queries.

First GET query: /mollie/checkout/process/?order_id=##&payment_token=##&utm_nooverride=1
REFERER: https://pay.klarna.com/

Second POST request: /mollie/checkout/webhook/?isAjax=1 with prametre [id=ord_##].

The second query occurs one second after the first.
Both queries cause the reservation to be cancelled.
The setting in the config `use_webhooks` has the value `enabled`.

**Comment by Frank-Magmodules** [comment] 2023-01-16 11:50
HI @gjportegies , 

Yes, that commit is indeed to prevent this issue from happening!

**Comment by Frank-Magmodules** [comment] 2023-02-27 13:59
HI There @gjportegies , thank you for your responses, it seems it's hard to reproduce.   
Can you please send us a [direct message](https://www.magmodules.eu/support-form.html) so we can take a look into your logs and setup?

**Comment by darektw** [comment] 2023-03-28 13:47
Hi @Frank-Magmodules  @gjportegies 
is there any new update?

**Comment by Frank-Magmodules** [comment] 2023-03-28 13:57
HI @darektw , please use the latest version indeed, if it's still there after the update, feel free to contact us [directly](https://www.magmodules.eu/support-form.html).
