### ISSUE TITLE
Order cant be shipped when customer NOT uses the PAYMENT LINK

### ISSUE THREAD

**Issue by b2bdokter** [mollie/magento2#481] opened 2022-01-19 09:56 UTC
# Describe the new feature

We use this module (Magento 2.4.1-p1 )  , and now got two orders that we cannot ship to set to complete.....

This occurs when: 
Order cant be shipped when customer NOT uses the PAYMENT LINK. Since the link is not used , the extension thinks the payment is open... but our customer has paid by banktransfer without letting us now upfront. Now the order cant be completed...

## Describe the solution to be implemented
The payment link has a option to manually set to paid, wich is not working on our installation. (Magento 2.4.1-p1 at the moment)

**Additional context**

**Comment by Frank-Magmodules** [comment] 2022-01-20 12:18
HI @b2bdokter ,

Thank you for opening this issue, specific for this reason there is a `mark as paid` button added within the order in case the "Allow to manually mark as paid?" option is set to yes in the `Payment Link / Admin Payment` configuration section within the Mollie plugin. This will simply finish the order and create a new one (-1) which can be invoiced/shipped again.

Based on the current information we can't reproduce this issue but please feel free to contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Comment by Frank-Magmodules** [comment] 2022-02-08 15:10
HI @b2bdokter ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our <a href="https://www.magmodules.eu/support-form.html">contact form</a> so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-02-08 15:10 UTC
Labels: Investigating

**Comment by simonmaass** [comment] 2022-10-28 13:33
We activated this option but we cannot see the button. Where would you find this button?

**Comment by Frank-Magmodules** [comment] 2022-10-31 08:27
HI @simonmaass , 

First, make sure that the option "Allow to manually mark as paid?" is set to `Yes` within the "Payment Link / Admin Payment" configuration section, just like below;

![](https://user-images.githubusercontent.com/24823946/198960178-17fe4760-8728-4706-9c99-dcf04d213406.png)

After that, the button should show up within the order as;

![](https://user-images.githubusercontent.com/24823946/198964305-4062e597-ada0-48da-8ee0-a3d99e8d2c08.png)

**Comment by simonmaass** [comment] 2022-11-01 09:34
Hey Frank, yeah we did all that. I think the problem is with scoping. We only activated the payment method for one store and also allowed to manually mark as paid for the store where we activated the payment method with payment link. Then the button does not show up! Only if you globally set the setting to "Yes"...

**Comment by simonmaass** [comment] 2022-11-22 16:30
@Frank-Magmodules please help!

**Comment by Frank-Magmodules** [comment] 2022-11-22 18:21
HI @simonmaass , I indeed think this is only working on global level within the admin, did you have tried that? Otherwise, feel free to [contact us](https://www.magmodules.eu/support-form.html) directly so we can take a look with you on this matter.
