### ISSUE TITLE
[BUG] "Mark as paid" created new order with wrong totals when using Custom Prices

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#745] opened 2024-02-15 12:24 UTC
**Describe the bug**
When clicking "Mark as paid" a new order is created and the old one is set to "Canceled".
The new order now has wrong totals!

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.34.0

**To Reproduce**
1. Create Order in admin backend with custom price on the product

<img width="527" alt="image" src="https://github.com/mollie/magento2/assets/32599710/77ca5580-c156-4cfb-99e5-f5c615084b6c">

3. Chose payment method "payment-link" for example
4. Create Order
5. When Order is in "payment pending" state click on "Mark as paid"

**Expected behavior**
New order is created with the same product totals as the old order!

**Actual behavior**
The new order is created with the original product price!

**Screenshots**
Old order:
<img width="1318" alt="image" src="https://github.com/mollie/magento2/assets/32599710/ffc9a0cd-b464-4a40-8bd7-85410292cb08">

New order:
<img width="1333" alt="image" src="https://github.com/mollie/magento2/assets/32599710/7be2564b-4f0f-4c37-822d-bc7424fc001f">

**Comment by simonmaass** [comment] 2024-02-15 14:58
Update: After doing some more research it seams like this bug only happens when you set the custom price to 0€... my first thought would be that some kind of truthy check fails with 0...

**Comment by Frank-Magmodules** [comment] 2024-02-26 09:02
Hi There @simonmaass ,Thank you for opening this issue. We were unable to reproduce this. Could you please try this on a plain Magento 2 installation with only Mollie installed to see if this issue is then still present? Thanks!

**Comment by simonmaass** [comment] 2024-03-04 16:40
@Frank-Magmodules I was able to reproduct the bug when setting a custom price to 0€:

Old order:

<img width="798" alt="image" src="https://github.com/mollie/magento2/assets/32599710/fcd22c1d-3d47-40cb-a585-8de22e70bc3e">


New order created by "Mark as paid":

<img width="796" alt="image" src="https://github.com/mollie/magento2/assets/32599710/7507152a-a17a-4d89-90ac-2720646fab20">

**Comment by Frank-Magmodules** [comment] 2024-03-12 09:44
Hello @simonmaass, I have replicated the issue now. It's indeed strange. I'll look into this with the team and provide you with an update shortly. Thank you for providing the additional information. It seems the problem is caused by the 0,00 number. We're not sure if it's Magento or Mollie responsible for this, but we'll investigate and find out.

**Comment by Frank-Magmodules** [comment] 2024-03-14 08:59
Hi There @simonmaass ,

Once again, thank you for opening this issue. It seems that this error is on the Magento side. 

To be even more precise, it is due to this line: 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/Quote/Item/Processor.php#L104
At that point `$customPrice === (int)0`, which returns false when compared with empty.

Since it appears to be a Magento-related problem rather than an issue specifically with the Mollie plugin, we will be closing this ticket for now.

**Closed by Frank-Magmodules** 2024-03-14 08:59 UTC
Labels: Bug, Question / Issue

**Comment by simonmaass** [comment] 2024-03-14 09:13
I found an open issue for magento for this:
https://github.com/magento/magento2/issues/36970

There is also an open pull request:
https://github.com/magento/magento2/pull/37625

**Comment by Frank-Magmodules** [comment] 2024-03-14 09:15
Perfect @simonmaass , thanks for sharing!
