### ISSUE TITLE
When using the Admin Payment Link it is possible to choose another payment option then selected

### ISSUE THREAD

**Issue by mtjweb** [mollie/magento2#354] opened 2021-02-08 12:10 UTC
**Describe the bug**
For several payment options i have set a surcharge. When I create an order in the admin and use the Admin Payment Link, I only select the payment option without a surcharge. Still the customer is able to choose one of the other payment options.

**Used versions**
- Magento Version number(eg 2.3.5): 2.3.5-p1
- Open source
- Mollie version number (Check configuration): v1.20.1
--

**To Reproduce**
1. Go to Sales => Orders
2. Create a new order
3. Select the Mollie Admin Payment Link as payment option
4. Select only one payment option to be used
5. Create order
6. Open the payment link in your browser.

**Expected behavior**
There should be no possibillity to use an other payment option then selected.

**Actual behavior**
It is possible to choose an other payment option then selected.

**Comment by Frank-Magmodules** [comment] 2021-02-11 08:02
HI @mtjweb ,

Thank you for opening the issue. I'm not able to reproduce this issue.  In the Mollie Payment screen, I can't select another payment method without the order being canceled. I've checked this with the iDeal payment method. 

Can you share the steps after step 6 as well and the chosen payment methods?

**Comment by mtjweb** [comment] 2021-02-11 09:25
I found the problem. It is in the email that is being send from Mollie. At the bottom is a link that let's the customer choose from all active payment options and not only the selected one.
![Knipsel](https://user-images.githubusercontent.com/16004337/107619459-7d960080-6c53-11eb-8a74-849a769b1576.PNG)

**Comment by Frank-Magmodules** [comment] 2021-02-11 09:38
HI @mtjweb , 

Got it, so this is only happening in case of a `banktransfer`, where Mollie also sends an email about the payment. 
If you chose another payment-method through that link, there is no `surcharge` calculated. 
Which is desired behavior for you in this case right?

**Comment by mtjweb** [comment] 2021-02-11 09:46
Yes, it is in the email when you choose banktransfer. When do not choose banktransfer, the customer doesn't receive an email from Mollie.

For me this link is a possibility for a customer to avoid the surcharge.

I think the link should be removed from the email. It is a loophole to the other payment options. When I want to offer other payment option to my customer I will selected the,m.

**Comment by MerijnMollie** [comment] 2021-02-11 15:39
Hi Mtjweb,

Sorry to hear that you're unhappy with the standard template for the bank transfer. This is unfortunately not regulated on platform nor shop level. Therefore, we've chosen to make that template as widely useable as possible (namely for every merchant using Mollie and bank transfer).
Adapting this for an edge case like this is unfortunately not possible. We have also never heard of big (any) scale abuse of this, just to avoid a payment fee.
We hope you understand the decision to keep the link as it is, to provide the best possible services for the biggest possible amount of merchants.

regards,
Merijn (Mollie)

**Comment by mtjweb** [comment] 2021-02-11 16:04
It happens to me regularly. Perhaps not on purpose, but it does cost me a lot of money because of the high average order amounts.

I find it strange that there is such a link in the bank transfer email.

Then there is nothing for me to do but to switch off a bank transfer by Mollie and to offer this payment option manually.

**Comment by MerijnMollie** [comment] 2021-02-16 07:53
HI mtjweb, thanks again for your input and thinking along.
We'll close this ticket for now. In case you find something else which we can address within the Magento plugin, please feel free to reach out anytime!

regards,
Merijn

**Closed** 2021-02-16 07:56 UTC
Labels: Investigating
