### ISSUE TITLE
[BUG] Issue creating creditmemo for orders with bundle products that are paid with Klarna

### ISSUE THREAD

**Issue by gjportegies** [mollie/magento2#755] opened 2024-03-04 13:14 UTC
**Describe the bug**
Unable to credit orders with bundle products that are paid via Karna.

 Mollie.ERROR: error: [2024-03-04T12:39:48+0000] Error executing API call (422: Unprocessable Entity): Cannot create a refund for these lines, the total amount shipped is zero.. Field: lines. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order-refund [] []

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.34.0

**To Reproduce**
1. Go to an order that is completed, has a bundle product and is paid with Klarna.
2. Click on the invoice and create a creditmemo.
3. Check the bundle product to refund.
4. Click on "Refund".
5. See error

**Expected behavior**
When a creditmemo is created we would expect Mollie to refund the given amound.

**Actual behavior**
The creditmemo is created in the Magento backend, but the order is not refunded in Mollie.
Or in most cases an error is thrown:

```
Mollie.ERROR: error: [2024-03-04T12:39:48+0000] Error executing API call (422: Unprocessable Entity): Cannot create a refund for these lines, the total amount shipped is zero.. Field: lines. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order-refund [] []
```

**Additional context**
If an order contains a bundle product combined with other simple or configurable products there is no error thrown in the backend. The problem then is that in Mollie only the simple products are refunded and not the bundle product.

**Comment by Frank-Magmodules** [comment] 2024-03-25 15:49
Hi There @gjportegies , could you find a moment to review this? As i'm eager to explore this issue with you!

**Comment by Frank-Magmodules** [comment] 2024-03-26 08:29
Oh, that's unfortunate for you @gjportegies , get well soon. We'll leave this open for now.

**Comment by Frank-Magmodules** [comment] 2024-04-09 09:36
Hello there, @gjportegies! I hope you're feeling better, of course. Have you managed to reproduce this on the latest version?

**Comment by Frank-Magmodules** [comment] 2024-04-15 07:52
Thanks for adding this, @gjportegies! With this new information, I'll look into the issue again and keep you updated.

**Comment by Frank-Magmodules** [comment] 2024-05-16 12:43
Hi There! 

We just released a [new version](https://github.com/mollie/magento2/releases/tag/v2.38.0) that addresses the bugs mentioned in this issue. Especially the comment from @Sental was very helpful, as it made the issue reproducible. 

It turned out that resuming an older existing transaction or order could sometimes throw an error, which resulted in various other bugs. These bugs are now solved, and the transaction ID is updated when a new transaction is started. 

We know for sure that the issue from @Sental should be fixed now. We think that the issue for @patricksteenks is also solved, but as we are unable to reproduce this issue it’s hard to say if this is really the case. 

We would love your feedback on this! I will leave the issue open till you both confirm it's all alright now.
Thanks people!

**Comment by Frank-Magmodules** [comment] 2024-05-16 13:00
Hi There @gjportegies , 

Thanks to your latest comment, we've successfully reproduced and resolved the issue in our [last release](https://github.com/mollie/magento2/releases/tag/v2.38.0)! Your detailed information and patience have been really valuable in troubleshooting. I'll mark this issue as closed for now, but please don't hesitate to reopen or comment if necessary. Thanks again!

**Closed as completed by Frank-Magmodules** 2024-05-16 13:00 UTC
Labels: Bug, Question / Issue, Fixed and planned for next release, Investigating
