### ISSUE TITLE
Cron issue with latest module 1.18

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#314] opened 2020-10-28 17:07 UTC
The latest module give the following cron error:

mollie_send_pending_payment_reminders : `Content must be string or resource; received "Magento\Framework\Phrase" `

**Comment by Frank-Magmodules** [comment] 2020-10-29 08:54
HI @JelleGe ,

Thank you for opening and reporting this issue. Seems we can't reproduce this in our own environment, can you please share some more information about this using our [bug report template](https://github.com/mollie/magento2/issues/new?assignees=&labels=&template=bug_report.md&title=)? 

Thanks!

**Comment by Frank-Magmodules** [comment] 2020-11-13 09:51
@JelleGe , any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by JelleGe** [comment] 2020-11-13 10:06
Hi Frank, we disabled the entire cron because we do not use it. So that solved the issue in our case, but I can not tell if this issue still occurs.

**Comment by Frank-Magmodules** [comment] 2020-11-20 13:22
Hi @JelleGe  ,
As discussed through e-mail, this problem no longer applies, we are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-11-20 13:22 UTC
