### ISSUE TITLE
payment status refresh for Klarna Pay Later gives unique constraint error

### ISSUE THREAD

**Issue by bamboekeizer** [mollie/magento2#195] opened 2019-08-29 14:26 UTC
Version 1.7.1, magento 2.3.2
Situation: Klarna Pay Later order. Order status in Mollie back-end is Authorised (GEAUTORISEERD)
Action: request payment status refresh from admin
Result: Error Tijdens Ophalen | Unique constraint violation gevonden

**Comment by Frank-Magmodules** [comment] 2019-08-29 20:13
HI @bamboekeizer , thanks for your message, seems we had this issue before but had it fixed in our latest release. I can't reproduce this on Magento 2.3.2 with Mollie 1.7.1. Can you sent us some server/back-end details through our [contact form](https://www.magmodules.eu/contact-us.html) so we can take a look with you?

Thanks!

**Comment by Frank-Magmodules** [comment] 2019-10-18 06:57
Closing the issue as this problem no longer occurs.

**Closed by Frank-Magmodules** 2019-10-18 06:57 UTC
