### ISSUE TITLE
Pending order state after succesfull payment

### ISSUE THREAD

**Issue by albsa** [mollie/magento2#79] opened 2018-09-27 10:42 UTC
Hi guys,

Since the upgrade to 2.2.6 the order state is kept in Pending after a succesfull payment.
The orderstatus it self is on processing.

Only when a shipment is create the state changes.

The mollie magento installed version is currently 1.3.7

**Comment by albsa** [comment] 2018-09-28 08:43
Coming back on this, checking in the database, the state is not "pending" but new.
Status = "Processing" , State = "new"

**Comment by albsa** [comment] 2018-09-28 08:59
@Frank-Magmodules

**Comment by Frank-Magmodules** [comment] 2018-09-28 09:01
Hi @albsa , Thanks for your messages on this. 
We are currently reproducing this in our environment so we can reproduce this and let you know the outcome and possible fix.

**Comment by albsa** [comment] 2018-09-28 10:14
@Frank-Magmodules Allright Frank, waiting for your update!

**Comment by highway11git** [comment] 2018-09-28 12:31
This might have to do with the pull request I opened.

https://github.com/mollie/magento2/pull/78

**Comment by Frank-Magmodules** [comment] 2018-09-28 14:11
HI @albsa , we are able to reproduce this on a fresh Magento CE 2.2.6 installation. 
As this was no problem on previous versions Magento version we've did some research and it looks very similar to this issue: https://github.com/magento/magento2/issues/18148 

We will let you know when we have more information on this.

**Comment by albsa** [comment] 2018-09-28 14:57
Damn Magento patches. Also the bundled products are even screwed up.
This order is also major issue imo regarding order management. 
@highway11git thanks I will look in to that part more.
@Frank-Magmodules I was thinking of maybe temprorary writing an observer that is checking for the succesfull capture. Change the state then to processing. However I am not a hardcore MG2 developer on that part yet. Do you suggest me too wait for you guys or? If we need to wait for the M2 patch, it might take a while.

**Comment by albsa** [comment] 2018-10-04 09:27
@Frank-Magmodules any updates from your end?

**Comment by Marvin-Magmodules** [comment] 2018-10-04 12:59
Hi @albsa

Just wrote a small workaround for his, see: https://github.com/mollie/magento2/commit/885e047a1b128af32e03a785d310d091e4f9904b

The RegisterCaptureNotification is not settings a processing state anymore, this comes from a recent [commit](https://github.com/magento/magento2/commit/f39138b6dc504f93dae9697ad45d11d57f1aaf1f#diff-68f9035e0545c5442dde19b0ba0fa9b4R38) fixing a issue for Paypal. Don't think this is intended, so I'm not merging this into a new version at this moment. Lets first wait for an official reaction / patch. 

Please let me know if this patch fixes your issues for now.

**Comment by Marvin-Magmodules** [comment] 2018-10-05 17:12
As there are no side effects, merged the fix into a new release; [v1.3.8](https://github.com/mollie/magento2/releases/tag/v1.3.8)

**Closed by Marvin-Magmodules** 2018-10-05 17:12 UTC
