### ISSUE TITLE
Invalid amount value for field unitPrice

### ISSUE THREAD

**Issue by Detzler** [mollie/magento2#542] opened 2022-07-04 17:20 UTC
**Used versions**
- *Magento Version number*:  2.3.3
- *Open source*
- *Mollie version number*: 2.13.0
- *PHP*: 7.1

**To Reproduce**
Simple checkout with any mollie payment method (select payment method and complete order)

**Actual behavior**
After clicking the order button in checkout, a redirect occurs to the cart page. An error is shown:

![image](https://user-images.githubusercontent.com/1556434/177196981-b789e62f-45d7-46a9-af6f-607b6989af4b.png)

Error executing API call (422: Unprocessable Entity): Order line 3 is invalid. Invalid amount value for field unitPrice.. Field: lines.3.unitPrice.value.

I digged in the mollie.log and saw negative price / amount values in the request entry:
![image](https://user-images.githubusercontent.com/1556434/177197285-15aef731-b8b5-42b1-a662-ad2945e2f5e1.png)

Disabling the adjustment order line helped temporarily:
![image](https://user-images.githubusercontent.com/1556434/177197412-270d73e4-e01e-40ea-8609-1a6540a399d3.png)

**Comment by Detzler** [comment] 2022-07-04 17:58
I digged deeper in vendor/mollie/magento2/Service/Order/Lines/Order.php::getAdjustment

![image](https://user-images.githubusercontent.com/1556434/177200986-1ca28af2-6556-4eff-aeee-20cea5afe646.png)

.. and made a var_dump on $difference
The result is: -1.7763568394003E-15

Read here about this kind of value:
https://stackoverflow.com/questions/35319109/php-difference-between-2-float-returns-a-very-big-result

**Comment by Frank-Magmodules** [comment] 2022-07-21 07:00
HI @Detzler ,   
  
Thank you for opening this issue! Based on the current information we can't see directly why this is happening. Therefore, can you please share more details of this environment with us through our secured [contact form](https://www.magmodules.eu/support-form.html)? Thanks a lot!

**Comment by Frank-Magmodules** [comment] 2022-08-05 09:13
HI @Detzler ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-08-05 09:13 UTC
Labels: Investigating

**Comment by jaybong** [comment] 2022-11-17 06:12
We are experiencing the same or a similar problem (unitPrice is -0.00 which causes an error. I've sent more details through your contact form.
