### ISSUE TITLE
Mollie Payments not functioning while using regular browser. However, Mollie is functional while using incognito browsing.

### ISSUE THREAD

**Issue by DjangoZeelig** [mollie/magento2#561] opened 2022-09-16 07:56 UTC
**Describe the bug**
While browsing in incongnito tab in chrome browser, I am able to use Mollie Payments in my local environment. However, when browsing regular I am not able to get past checkout, and i am stuck at the loading symbol of the page.

**Used versions**
- *Magento Version number*: 2.4.2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration): 2.16.0.
- *Chrome Version 105.0.5195.125

**To Reproduce**
1. Put items in shopping cart.
2. Go to payments.
3. In incognito browsing: I am able to succesfully make a payment. (see screenshot below)
4. In regular browsing: I am stuck in checkout page, and only see a loading page symbol.

**Expected behavior**
I would expect no difference between regular and incognito use of browser.

**Actual behavior**
In regular mode, stuck at checkout page. In incognito mode, able to make a payment.

**Screenshots**
![Mollie test](https://user-images.githubusercontent.com/100681012/190586193-91b76bcf-56f1-4e36-9527-cd6b8a34de4d.png)

**Additional context**
-

**Comment by Frank-Magmodules** [comment] 2022-09-19 15:23
@DjangoZeelig ,

Thanks for opening this issue. We can’t seem to reproduce this issue. Could you please open your console while navigating through the checkout and check for any errors?

**Comment by Frank-Magmodules** [comment] 2022-10-03 11:27
Hi @DjangoZeelig ,

Seems we don't have a response on this yet, can you please [contact us](https://www.magmodules.eu/support-form.html) for more information or close this issue if there is no help needed anymore? Thank you!

**Comment by Frank-Magmodules** [comment] 2022-10-05 06:43
@DjangoZeelig ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-10-05 06:43 UTC
Labels: question
