### ISSUE TITLE
Error in backend orders, NL

### ISSUE THREAD

**Issue by visualwebs** [mollie/magento2#426] opened 2021-09-02 19:02 UTC
**Describe the bug**
I have region as optional for NL. When I try to create backend orders I receive the error in the image because region is null

![backend_error](https://user-images.githubusercontent.com/6909746/131901157-b023fbcf-b1d5-44a8-ae6c-fec7603d22bc.gif)

I need to create a plugin for resolve 

```
use Magento\Sales\Model\Order\Address;

class AddressPlugin
{
    public function afterGetRegion(Address $subject, $result)
    { 
        return (string)$result;
    }
}
```

**Used versions**
- Magento 2.4.2-p1 Open source
- Mollie version number (1.30)

**To Reproduce**
1. Go to backend, create order
2. Select Mollie as payment
3. Create the order
4. The error appears in the notification area

**Comment by Frank-Magmodules** [comment] 2021-09-07 09:55
Hi @visualwebs ,

Thank you for opening this issue, it seems we can't reproduce this issue in our environments. Can you please reproduce this in a test environment and share the details with us through our secured [contact form](https://www.magmodules.eu/support-form.html)?

Thanks!

**Comment by Frank-Magmodules** [comment] 2021-09-29 08:23
Hi @visualwebs ,

We didn't receive any details on this issue yet, can you please share this so we can investigate this issue?

**Comment by visualwebs** [comment] 2021-10-02 06:20
Hi, currently happens in a very customized store. If you consider this is not reproducible in your side you can close the issue.
Only want to help when I discover a problem and maintain the module free of bugs.

Enviado desde Correo para Windows

De: Frank Tiggelman
Enviado: martes, 7 de septiembre de 2021 11:55
Para: mollie/magento2
CC: Francisco Díaz; Mention
Asunto: Re: [mollie/magento2] Error in backend orders, NL (#426)

Hi @visualwebs ,
Thank you for opening this issue, it seems we can't reproduce this issue in our environments. Can you please reproduce this in a test environment and share the details with us through our secured contact form?
Thanks!
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Frank-Magmodules** [comment] 2021-10-04 08:56
Hi @visualwebs , 

Thank you for your reply on this, we will close this issue now but please feel free to reopen in case you still have issues or when you have new insights on the issue.

**Closed by Frank-Magmodules** 2021-10-04 08:56 UTC
Labels: Investigating
