### ISSUE TITLE
Error while checking if topic is synchronous

### ISSUE THREAD

**Issue by HyperC** [mollie/magento2#750] opened 2024-02-26 13:17 UTC
We're experiencing an issue with the upgrade to the latest version of this module (2.35.0). During the setup:upgrade we get the following error:

_Error while checking if topic is synchronous_

We've added the exception message, which results in:

_Error while checking if topic is synchronous **Topic "mollie.transaction.process" is not configured.**_

In the latest version, a communication.xml file has been added with this topic. Is specific configuration needed for the setup:upgrade to succeed?

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.35.0

**To Reproduce**
1. Upgrade to latest version
2. Set to production mode (run di:compile and static-content:deploy)
3. Run setup:upgrade
4. See error:
> Updating modules:
> ...
> Module 'Magento_MysqlMq':
> Error while checking if topic is synchronous

**Comment by Frank-Magmodules** [comment] 2024-02-26 15:13
Hi There @HyperC ,

Thank you for opening this issue. There should no extra configuration be required to run `setup:upgrade`.  When developing and releasing this extension, `setup:upgrade` is run multiple times, so we are sure that it runs fine without extra configuration. I suspect that you have an extra module or configuration set that causes this problem. Could it be that you have an extra configuration in your `app/etc/env.php` regarding consumers?

**Comment by Frank-Magmodules** [comment] 2024-02-26 19:57
Thank you, @HyperC , for providing additional information. However, based on the details provided, we are unable to allocate the issue. Could you please share further details about your environment [directly](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) with us? This will enable us to investigate the issue more effectively together. Thank you!

**Comment by Hnto** [comment] 2024-03-04 18:51
@Frank-Magmodules I can confirm that we're also having this issue during deployment. I'm still trying to debug by removing our custom modules one by one, but it still gives an error.

**Comment by Frank-Magmodules** [comment] 2024-03-19 13:03
Hello @Hnto , despite previously sharing some information, we are still encountering difficulties reproducing this issue. Could you please [reach out](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) to us with additional details? Your assistance would be greatly appreciated. Thank you.

**Comment by qsolutions-pl** [comment] 2024-03-27 06:11
I've reproduced this issue on 3 instances

**Comment by Frank-Magmodules** [comment] 2024-03-27 06:36
Thank you for providing a possible solution here as well, @qsolutions-pl. It's really helpful since we were unable to replicate it effectively with other merchants or locally. We'll review your suggestion and incorporate it into the upcoming release if it resolves the issue and gains approval from our end. Thanks once more! Surely we will update this ticket once the release is there!

**Comment by qsolutions-pl** [comment] 2024-03-27 08:57
@Frank-Magmodules it only worked once, when Rabbit MQ is enabled, we cannot process with `setup:upgrade` command 
The configuration passed to topic is not recognized by the framework
```
string(26) "mollie.transaction.process"
NULL
Error while checking if topic is synchronous
```

`NULL` - is the topic configuration

here is snapshot from `queue` config from `env.php` file
```php
    'queue' => [
        'amqp' => [
            'host' => 'localhost',
            'port' => '5672',
            'user' => 'project,
            'password' => 'projectPassword',
            'virtualhost' => 'projectHost',
            'ssl' => ''
        ],
        'consumers_wait_for_messages' => 1
    ],
```

**Comment by qsolutions-pl** [comment] 2024-03-27 08:58
On our end we will have to disable the AMQP and run all consumers via CRON

**Comment by qsolutions-pl** [comment] 2024-03-27 10:30
@HyperC  on our end it turned out that it was an issue with REDIS configuration. It was not cleared upon deployments or it was not even cleared on any `php bin/magento c:clean` or `flush` commands. 
We ruin into this issue from time to time on various projects, but never with the RabbitMQ configuration.
@Frank-Magmodules  we've disabled REDIS and it works with and without the patch you have provided. 
Imho, this issue is not code related and can be closed.

**Comment by HyperC** [comment] 2024-03-27 10:50
@qsolutions-pl Thanks for looking in to this issue! Did you re-enable redis after successful deployment? And the handler you mentioned is also not necessary then?

**Comment by qsolutions-pl** [comment] 2024-03-27 11:15
@HyperC  to be fair, I'm not entirely sure the handler is required. 
As @Frank-Magmodules  mentioned, they cannot replicate the issue, nor can we on instances where we've disabled the redis for config.
We have not reenabled it, most projects we handle run on a single servers (each project has it's own) with fast NVMe SSD drives, so disabling REDIS for the config cache does not affect the performance.

**Comment by HyperC** [comment] 2024-03-28 09:39
@qsolutions-pl Could you maybe share your env config? Did you just add something like this to your frontend cache?
```
'config' => [
            'backend' => 'Magento\Framework\Cache\Backend\File',
            'backend_options' => [
                'cache_dir' => ''
            ],
        ],
```

Wouldn't it also be enough to just flush redis cache just before performing the setup:upgrade in the deploy script?

**Comment by HyperC** [comment] 2024-03-29 07:20
@qsolutions-pl And one more question on your handler change:

```<topic name="mollie.transaction.processor" is_synchronous="false" request="Mollie\Payment\Api\Data\TransactionToProcessInterface" response="boolean">
        <handler name="mollie.transaction.processor.handler" type="Mollie\Payment\Queue\Handler\TransactionProcessor" method="execute" />
    </topic>```

You changed the topic name from `mollie.transaction.process` to `mollie.transaction.processor`. Was this intentional?

**Comment by qsolutions-pl** [comment] 2024-03-29 07:50
it was intentional, but as I've mentioned earlier, it was not needed, once we cleared the REDIS entirely, all code worked. 
Maybe it is needed in earlier versions of Magento, what is your project M2 version?

**Comment by HyperC** [comment] 2024-03-29 07:52
We're running the latest version 2.4.6-p4

**Comment by qsolutions-pl** [comment] 2024-03-29 07:58
Are you still experiencing this error ?

**Comment by HyperC** [comment] 2024-03-29 08:00
Yes. Just on our production environment unfortunately. We're going to try another deploy with a redis-cli flushall just before the setup:upgrade.

**Comment by HyperC** [comment] 2024-03-29 08:28
Deploy failed again initially. I ran `set:up --keep-generated` manually again, and it succeeded. The only thing I fear is that future deploys will run into this issue again. But we'll see.
Thanks for the help!

**Comment by Frank-Magmodules** [comment] 2024-03-29 08:39
Great teamwork, gentlemen! I'm happy to see that you've reached a solution together. Just to make sure, can you confirm if we can close the issue for now, @HyperC and @qsolutions-pl? Thanks!

**Comment by HyperC** [comment] 2024-03-29 08:40
@Frank-Magmodules Yes, issue can be closed :)

**Comment by Frank-Magmodules** [comment] 2024-03-29 09:07
Great guys, thanks again and; happy Easter!

**Closed by Frank-Magmodules** 2024-03-29 09:07 UTC
Labels: Question / Issue

**Comment by qsolutions-pl** [comment] 2024-03-29 12:05
> Deploy failed again initially. I ran `set:up --keep-generated` manually again, and it succeeded. The only thing I fear is that future deploys will run into this issue again. But we'll see. Thanks for the help!

It is possible that the old release code and it's configuration was loaded from `Redis` - this is what happend to us.
