### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by DjangoZeelig** [mollie/magento2#557] opened 2022-09-12 10:56 UTC
**Describe the bug**
Getting following error: Your requirements could not be resolved to an installable set of packages.
After trying to install via composer require mollie/magento2.

**Used versions**
- *Magento Version number 2.4.2.
- Composer Version number 2.2.17.
- Magento/framework version 103.0.2.
- *Open source/Enterprise/B2b*: open source.
- *Mollie version number (Check configuration)*: 2.16.0.

**To Reproduce**
1. Go to root of project.
2. via command line: composer require mollie/magento2
4. See following error:
Problem 1
Root composer.json requires mollie/magento2 ^2.16 -> satisfiable by mollie/magento2[2.16.0].
mollie/magento2 2.16.0 requires magento/framework >=102.0.3 -> could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Expected behavior**
I would have expected that requirements are met and that an installation would give no problems.

**Actual behavior**
Installation failed, deleting ./composer.json.

**Screenshots**
![Screenshot from 2022-09-12 12-56-00](https://user-images.githubusercontent.com/100681012/189636807-e83997e2-79eb-4ee0-aaf8-e2115d9a9161.png)

**Additional context**
Tried installing from correct Magento root directory. See update in comments below.

**Comment by Marvin-Magmodules** [comment] 2022-09-12 11:02
@DjangoZeelig are you sure you are running this in Magento root directory as it states in the screenshot it is trying to create the composer.json instead of updating it?

**Comment by DjangoZeelig** [comment] 2022-09-12 11:46
@Marvin-Magmodules Thank you for your insight.
I tried installation from the correct Magento root directory. This gave the following errors:
![Screenshot from 2022-09-12 13-35-57](https://user-images.githubusercontent.com/100681012/189645202-994c992e-e1a5-44dd-b57b-aa2aed6ea52e.png)

**Comment by Frank-Magmodules** [comment] 2022-09-19 17:07
HI @DjangoZeelig , 

Not sure what's happening here and if this is an issue with the Mollie plugin or your Magento environment but surely we are happy to help you out on this and your other, probably, environment-related issue. Feel free to contact us with more details and credentials through our secured [contact form](https://www.magmodules.eu/support-form.html).

**Comment by Frank-Magmodules** [comment] 2022-10-03 11:30
HI @DjangoZeelig , is this issue still happening to you? Feel free to contact us or please close this ticket in case you don't have this issue anymore.

**Comment by Frank-Magmodules** [comment] 2022-10-05 06:44
HI @DjangoZeelig ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-10-05 06:44 UTC
Labels: question
