### ISSUE TITLE
Cannot refund Payment Surcharge

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#381] opened 2021-04-26 08:44 UTC
**Describe the bug**

We added a 2% surcharge for PayPal. If you make a full refund for the order with surcharge you cannot refund the surcharge.

**Used versions**

- Magento Version 2.4.2
- Open source
- Mollie Version: 1.22

**Screenshots**

![order](https://user-images.githubusercontent.com/53861858/116053919-73dd4000-a67b-11eb-8950-77929266ed1c.png)

![invoice](https://user-images.githubusercontent.com/53861858/116053917-73dd4000-a67b-11eb-9003-7896803c5bb8.png)

![credit-memo](https://user-images.githubusercontent.com/53861858/116053914-7344a980-a67b-11eb-8080-35f60fb15172.png)

**Comment by Frank-Magmodules** [comment] 2021-04-28 09:19
HI @tropilex ,

Thank you for opening this issue, seems I can't reproduce this issue on the latest Mollie version. Can you please update the plugin to the latest version and let me know if you are still able to reproduce this?

Thank you!

**Comment by Frank-Magmodules** [comment] 2021-05-06 08:55
HI @tropilex ,
Any update on this issue?

**Comment by tropilex** [comment] 2021-05-06 08:59
@Frank-Magmodules We still have the issue. But we did not update the plug-in yet. I will keep you updated.

**Comment by Frank-Magmodules** [comment] 2021-06-25 10:51
Any update on this, @tropilex? :smirk:

**Comment by tropilex** [comment] 2021-06-25 10:56
@Frank-Magmodules Almost. ;-) We couldn't update to the latest version because the staging server is busy. I will soon have an update.

**Comment by tropilex** [comment] 2021-07-22 09:07
@Frank-Magmodules  We updated to the latest version. We still got this issue.

Screenshots in first post are also apply to orders / payments after the update.

**Comment by Frank-Magmodules** [comment] 2021-07-26 09:14
Hi @tropilex ,

I think this has to do with your other issue #389, therefore, I close this issue now so we can continue debugging and fixing this issue together with #389 directly.

**Closed by Frank-Magmodules** 2021-07-26 09:14 UTC
Labels: Investigating
