### ISSUE TITLE
Upgrading from 2.20 to 2.20.1 set timestamp of order in backend to 01.00AM

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#603] opened 2023-01-21 14:54 UTC
**Describe the bug**
After we upgrade from 2.20 to 2.20.1 all new orders got a timestamp in Magento at 1:00:00 AM the day the order is placed.
The order really receive this timestamp, because we can also find in the DB.

Reverting back to 2.20 solved the issue for all new orders.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4-p2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.20.1

**To Reproduce**
1. Upgrade from 2.20 to 2.20.1
2. Place a new order using a Mollie method.
3. The order will receive the timestamp of 1:00:00 AM.

**Comment by Frank-Magmodules** [comment] 2023-01-24 18:27
Hi @JelleGe ,

Is this still going on?
We've tried to find a reason for this so we could reproduce the issue but didn't succeed. 
Can you please [contact us](https://www.magmodules.eu/support-form.html) directly so we can take a look with you? Thanks a lot!

**Comment by JelleGe** [comment] 2023-01-25 11:58
Hi @Frank-Magmodules,

Thanks for the reply.

We just submitted the contact form.

**Comment by Frank-Magmodules** [comment] 2023-02-13 08:44
HI @JelleGe ,

We investigated this issue further and came to the conclusion that this issue is caused by **custom code** on your end in the app/code/Amasty/PDFCustomNewFormatDate folder. 

We've specified it through e-mail. For now, we will close this issue. 
Have a good day!

**Closed by Frank-Magmodules** 2023-02-13 08:44 UTC
Labels: question
