### ISSUE TITLE
Mollie no longer on  frontend after changing to production mode

### ISSUE THREAD

**Issue by aqdennis** [mollie/magento2#248] opened 2020-04-26 10:56 UTC
I had Mollie working fine in both test and live mode while my website was still not live and in developer mode. Now the website is live and in production mode and Mollie payment options do not appear on the frontend anymore, but other payment methods do (including from our former PSP, ING Bank).

When going into production mode I made several changes that I cannot all recall, but none of them seem to be related to why Mollie won't show anymore:

- Upgraded PHP from 7.1 to 7.3
- Changed DNS records at our domain provider to point to this new webshop
- Put Magento into Production mode
- Installed MagePlaza SMTP extension to be able to send sales e-mail through GMAIL
- Installed FooMan order number extension to synchronize invoice number with order number
- Uninstalled MageArray Calendar extension as it didn't work as we wanted.

What I tried and checked:
- I went through the whole checklist and that seems to be all fine.  
- TestAPI gives me the payment methods I have activated
- Test gives me green check marks for PHP version and JSON
- Tried to uninstall (Composer remove -> setup:upgrade -> di:compole -> deploy static-content, clean cache) and reinstall but without success

Running Magento 2.3.2 ....

**Comment by Frank-Magmodules** [comment] 2020-04-27 08:08
Hi @aqdennis ,

We are not able to reproduce this on a vanilla Magento 2.3 instance. Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) to send us your frontend URL so we can check this?

Frank

**Comment by Frank-Magmodules** [comment] 2020-05-07 09:17
Hi @aqdennis, thanks again for the detailed issue report. The issue has been resolved in the [v1.13.0](https://github.com/mollie/magento2/releases/tag/v1.13.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-05-07 09:17 UTC
