### ISSUE TITLE
Error when creating credit memo

### ISSUE THREAD

**Issue by GetMagented** [mollie/magento2#227] opened 2020-03-17 13:19 UTC
After installing the newest version (7 days agao) of this extension we get this error when we want to create a new credit memo:

Fatal error: Uncaught Error: Call to a member function setMolliePaymentFee() on null in /data/web/magento2/vendor/mollie/magento2/Plugin/Sales/AddPaymentFeeToOrder.php:41 Stack trace: #0 /data/web/magento2/vendor/mollie/magento2/Plugin/Sales/AddPaymentFeeToOrder.php(30): Mollie\Payment\Plugin\Sales\AddPaymentFeeToOrder->addMolliePaymentFeeTo(Object(Magento\Sales\Model\Order\Interceptor)) #1 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(146): Mollie\Payment\Plugin\Sales\AddPaymentFeeToOrder->afterGet(Object(Magento\Sales\Model\OrderRepository\Interceptor), Object(Magento\Sales\Model\Order\Interceptor), '111321') #2 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('111321') #3 /data/web/magento2/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(26): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins('get', Array, Array) #4 /data/web/magento2/vendor/m in /data/web/magento2/vendor/mollie/magento2/Plugin/Sales/AddPaymentFeeToOrder.php on line 41

We're running Magento 2.2.3 and to not use the payment fee's at this moment.

**Comment by Frank-Magmodules** [comment] 2020-03-17 14:35
Hi @GetMagented , 
Thank you for your message.
Did you already executed the  `setup: di: compile`command after the update?

**Comment by GetMagented** [comment] 2020-03-19 14:58
Hi @Frank-Magmodules yes we did. Just to be sure I ran it again just now but the same error persists.

**Comment by Frank-Magmodules** [comment] 2020-03-19 15:04
HI @GetMagented , strange. As we can't reproduce this, can you please send us more information on this through our [contact form](https://www.magmodules.eu/support-form.html) so we can help you out?

**Comment by Frank-Magmodules** [comment] 2020-03-25 13:56
Hi @GetMagented, thanks again for the detailed issue report. The issue has been resolved in the [v1.12.0](https://github.com/mollie/magento2/releases/tag/v1.12.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-03-25 13:56 UTC
