### ISSUE TITLE
curl timeout 28 error

### ISSUE THREAD

**Issue by KiranLankapalli** [mollie/magento2#437] opened 2021-10-12 12:07 UTC
Hi,
I have added the api keys in the module from mollie account, and when click on Test API keys button gives the following errors:
Test API-key: [2021-10-12T12:04:44+0000] cURL error 28: Resolving timed out after 2513 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
![Screenshot from 2021-10-12 17-39-08](https://user-images.githubusercontent.com/90908119/136953482-44d67084-9f40-42c8-a0ba-904e6c6dd206.png)

**Comment by Frank-Magmodules** [comment] 2021-10-14 13:16
HI @KiranLankapalli ,

Thank you for opening this issue, it seems that we can't reproduce this issue but it seems there is breaking something during this cURL request. Do you have this issue all the time? If possible, please share your store details and/or the other relevant log files using our [contact form](https://www.magmodules.eu/support-form.html) so we can help you with this.

Thank you!

**Comment by Frank-Magmodules** [comment] 2021-12-06 09:28
Hi @KiranLankapalli ,

We've had some internal discussions on this issue and it seems there are no other Magento users with this issue, we want to investigate this case together with you. So if possible, please share your store details and/or the other relevant log files using our [contact form](https://www.magmodules.eu/support-form.html) so we can help you with this or close this issue in case this is already solved from your end.

**Comment by AmandaMollie** [comment] 2021-12-16 14:25
We're going to close this issue now due to inactivity. Please feel free to reopen if the issue still persists.

**Closed by AmandaMollie** 2021-12-16 14:25 UTC
Labels: Investigating
