### ISSUE TITLE
[BUG] Klarna Pay Later - Order Items are not marked as invoiced

### ISSUE THREAD

**Issue by mvenghaus** [mollie/magento2#734] opened 2024-01-23 11:10 UTC
**Describe the bug**
When creating an invoice via rest api the invoice is created, but the order items doesn't have a "qty_invoiced", etc.. It's only happing on Klarna Pay Later .. is this on purpose?

**Used versions**
- 2.4.6-p3
- Open source
- 2.33.0

**To Reproduce**
1. Create an order with Klarna Pay Later
2. Trigger invoice via REST API
3. Look in "sales_order_item" .. column "qty_invoiced"

**Expected behavior**
qty_invoiced > 0

**Actual behavior**
qty_invoiced  = 0

**Comment by Frank-Magmodules** [comment] 2024-02-19 08:31
Hello @mvenghaus, my apologies for the delayed response.

Thank you for opening this issue. You are following a bit of a weird path with this order. You don’t need to create the invoice yourself: "We" do that for you. You just need to ship the order, then the invoice is created for you. 

If you don’t want to wait for the order to ship you also change the setting of `Stores -> Configuration -> Mollie -> Advanced -> Triggers & Languages -> When to create the invoice? `to “On Authorize”. Then it will be created when the order has been placed and authorized.

**Comment by mvenghaus** [comment] 2024-02-19 08:39
Hey @Frank-Magmodules ,

no problem. I think my description is bad ;)

I do ship the order, i don't create the invoice myself. The invoice is created on shipping, but the qty (table sales_order_items | qty_invoiced) is not set .. the invoice looks okay. It works with other payment methods, that's why i reached out here .. you're my last hope ;)

**Comment by Frank-Magmodules** [comment] 2024-02-19 09:54
That's fast! @mvenghaus. We attempted to replicate the issue but were unsuccessful. Could you please provide additional details through [this link](https://www.magmodules.eu/help)? This will help us investigate further alongside you.

**Comment by Frank-Magmodules** [comment] 2024-02-26 08:34
Hello @mvenghaus , we haven't received the necessary information regarding this issue yet. Since we're unable to reproduce it on our end, it would be greatly appreciated if we could delve deeper into it together to find a solution. Thank you! :)

**Comment by Frank-Magmodules** [comment] 2024-03-25 19:33
Hi There @mvenghaus. Because there hasn't been any recent activity regarding this issue, we've made the decision to temporarily close it. However, if you continue to experience this problem, please don't hesitate to reach out to us directly. We'll be more than happy to assist you further.

**Closed by Frank-Magmodules** 2024-03-25 19:33 UTC
Labels: Question / Issue, Investigating
