### ISSUE TITLE
Wrong Invoice / Order State currupt

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#786] opened 2024-06-14 11:24 UTC
**Describe the bug**
We cannot really pin point the problem but can only describe the bug at the moment. We will try to collect more data over time...

We have noticed that a couple of orders are getting currupt after wrongfully created invoice.

The payment process looks fine looking at the comment history:
<img width="400" alt="image" src="https://github.com/mollie/magento2/assets/32599710/6a4ed22d-24a3-48e7-acce-3e77db5ed78d">

Mollie webhook log:
<img width="266" alt="image" src="https://github.com/mollie/magento2/assets/32599710/449e1ab0-c9a4-4168-b45c-2ee4c32d7dc1">

But as you can see, the order was created on the 10.06 but there is an order status update on the 12.06:
<img width="545" alt="image" src="https://github.com/mollie/magento2/assets/32599710/af4c4a00-2de3-466f-9195-16ee7ab671b1">

The order is now currupt as there is an invoice but the order items are not correctly labeled as "invoiced":
<img width="839" alt="image" src="https://github.com/mollie/magento2/assets/32599710/11e3d506-5292-431f-906e-405089d24463">

Possible ideas what the problem might be: 0€ priced products? Just an idea...

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p5
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: v2.37.0

**To Reproduce**
Cannot really pin point the bug at the moment...

**Expected behavior**
The order should have the correct state "Processing" with a propper invoice.

**Actual behavior**
"Currupt" order state as you are not able to create annother invoice nor are you able to propperly ship the items...

What is strange is that there is not webhook on mollie side that is responsible to trigger the "again" new processing state on the 12.06....

**Comment by Frank-Magmodules** [comment] 2024-06-17 11:23
Hi @simonmaass,

Thank you for opening this issue. Could you please try to reproduce the problem with the same order in a staging or development environment? I haven't been able to replicate it on our end. Could you also clarify the product type for the "`Rezeptgebuhr`" item line? Additionally, I noticed that the item status for what seems to be a simple product is set to backorder, maybe this can also influence this process?

Additionally, if you can reproduce the issue on a clean/vanilla Magento instance, please share the details with us directly so we can assist you further. You have our contact information. 😊

**Comment by julia211091** [comment] 2024-06-18 07:17
I have the same problem, using 2.38.0 (I only updated last week, before we had an older version (2.2x.x, I don't remember the exact version), where the problem didn't occur.
Maybe the backorder can be a hint, both orders, my colleague just provided me, contained backorder products.
Unfortunately I cannot provide a test system right now, so hopefully @simonmaass can.
Regards
Julia

**Comment by Quazz** [comment] 2024-06-25 13:12
Manual fixes for these orders would be to do something like the following:

Search for the order by order_id in mollie_payment_transaction_to_order table.

I'm guessing you will have multiple entries here (likely 2) for the affected orders.

The earlier entry should contain the correct transaction_id

Copy that and paste it in sales_order table for the correct order.

Now open that order in magento backend and click on "fetch status" under payment information.

For some reason, in certain circumstances more than one transaction is started. The first one successfully finishes; but then a second entry is logged which puts the order on "pending" (and cancelled after a while if you have auto cancel enabled)

**Comment by Frank-Magmodules** [comment] 2024-06-26 09:22
Hi @simonmaass and @Quazz, could you please [share](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) the debug log and possibly the access log as well? With the current information, I'm unable to reproduce or identify the issue. Let's investigate this together.

**Comment by Quazz** [comment] 2024-06-26 10:56
> Hi @simonmaass and @Quazz, could you please [share](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) the debug log and possibly the access log as well? With the current information, I'm unable to reproduce or identify the issue. Let's investigate this together.

Is there a way to send this privately since it contains personal information of customers?

I see a lot of activity in the debug log concerning the orders that have issues, even long after the order has been processed already.

**Comment by simonmaass** [comment] 2024-06-27 13:14
> I haven't been able to replicate it on our end. Could you also clarify the product type for the "`Rezeptgebuhr`" item line? Additionally, I noticed that the item status for what seems to be a simple product is set to backorder, maybe this can also influence this process?

Rezeptgebühr is a "virtual" product. I dont believe the "backorder" should have any impact...

**Comment by julia211091** [comment] 2024-06-28 06:42
I have every day several of that issues. I enabled last night the debug mode of the mollie extension. I will send you the mollie.log file via mail. Which access log you're looking for? the server log? Or system.log?
Regards
Julia

**Comment by Frank-Magmodules** [comment] 2024-06-28 08:00
Thank you for sending over your debug log, @julia211091. I will review it and get back to you shortly.

**Comment by Frank-Magmodules** [comment] 2024-07-01 08:25
Hi there @julia211091 , @Quazz  and @simonmaass , 
could you check if you maybe have the loading screen enabled? 

The functionality has been deprecated a while ago, but it’s still available:
`SELECT * FROM `core_config_data` WHERE `path` = 'payment/mollie_general/loading_screen'
`

We suspect that this screen is the cause of these issues. To be more precise: When users use the “back” button after making the payment and going back to this page. You can disable it by removing the record from your `core_config_data` table.

**Comment by simonmaass** [comment] 2024-07-01 08:30
Hey @Frank-Magmodules , we are using magento via API with a PWA as frontend. I am not sure what this config does but it seems like it is a frontend user related feature that is not impacting us. PS. also the feature is disabled

**Comment by julia211091** [comment] 2024-07-01 09:24
Hi Frank,
the value was indeed set to 1. I just removed the record and will give you a response tomorrow if there were any new issues in the next 24 hours.
But as I updated the extension lately, it is most likely the case.
Regards
Julia

**Comment by Quazz** [comment] 2024-07-01 14:54
@Frank-Magmodules 

Thanks, deleted the value from DB. Will monitor the situation; it didn't happen very frequently so might take some time.

**Comment by julia211091** [comment] 2024-07-05 08:59
Hello,
just wanted to give my feedback: since removing the value from the database, the problem is resolved.
Regards
Julia

**Comment by Frank-Magmodules** [comment] 2024-07-05 09:24
Thanks @julia211091, that's encouraging! I'll also wait for @Quazz's response so we can resolve the issue with a positive outcome.

**Comment by Frank-Magmodules** [comment] 2024-07-12 11:33
Hi All,

I'm happy to inform you that we've covered this case in the [latest release](https://github.com/mollie/magento2/releases/tag/v2.40.0). Thank you for your report and information from all. I'm closing this issue for now, but feel free to reopen it or comment whenever needed.

Have a great weekend!

**Closed by Frank-Magmodules** 2024-07-12 11:33 UTC
Labels: Investigating
