### ISSUE TITLE
No Klarna in the checkout after switching to the single Klarna solution

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#813] opened 2024-09-06 11:43 UTC
**Describe the bug**
We switched to the single Klarna method instead of the different Klarna methods. 
See this article: https://help.mollie.com/hc/en-gb/articles/20406623599890-Klarna-Migration

Unfortunately, we don't see the Klarna method in the checkout.

**Used versions**
- Magento 2.4.7
- Open source
- Mollie version number 2.40.1

**Screenshots**
![Screenshot 2024-09-06 at 13 36 53](https://github.com/user-attachments/assets/e8b0a831-429e-4984-b32e-7e29e7096e3c)
Activated in Mollie.

![Screenshot 2024-09-06 at 13 35 37](https://github.com/user-attachments/assets/31fe7f7f-bae8-424a-891f-be862750d53b)
Activated in Magento.

![Screenshot 2024-09-06 at 13 35 13](https://github.com/user-attachments/assets/b87cd35d-140c-48a6-ac01-0888f8f977fe)
Not visible on the front-end.

**Comment by Frank-Magmodules** [comment] 2024-09-10 08:57
Hi @tropilex,   It looks like you're using the correct Klarna payment method in the Magento configuration. Could you double-check if the "payment from specific countries" option is properly configured and saved at the store level as well? As I can't reproduce the issue as you describe. Thank you!

**Comment by tropilex** [comment] 2024-09-10 10:16
Hey @Frank-Magmodules. Just did a double check and everything is correct. Emptied the cache but that also didn't work.

I tested it with "All allowed countries." But without succes.

Other domain for different countries on the same Magento install also do not work.

**Comment by tropilex** [comment] 2024-09-10 10:20
@Frank-Magmodules Found that it's working on our United Kingdom store. Good to know is that the single Klarna method was always activated for the UK and we also got orders through Klarna.

**Comment by tropilex** [comment] 2024-09-10 11:21
@Frank-Magmodules Mollie is aware of this.

![Screenshot 2024-09-10 at 13 21 14](https://github.com/user-attachments/assets/abfb737e-03a9-4416-9188-d04df32654c4)

**Comment by Frank-Magmodules** [comment] 2024-09-10 11:37
Perfect, thanks for putting in the effort @tropilex! You’re ahead of me on this one, but I’m glad we’ve identified the cause!

**Comment by Frank-Magmodules** [comment] 2024-09-13 06:58
Hi @tropilex, just checking in—did you expect anything further regarding the Mollie module itself? If not, I’m happy to close this issue. We’ll address the UI cleanup for Klarna Payment Methods in a future release.

**Comment by tropilex** [comment] 2024-09-13 08:02
@Frank-Magmodules It's not fixed yet. I got a message back from Mollie what is also strange. In their testing shop it's only working when you select "All allowed countries". 

```
Dear Kees,
 
I am Angelique from the Tech support team. Your question has been forwarded to me. 
 
I have understood that the new Klarna option is not shown in the checkout of all your shops except of the UK one. I have done some testing in our test shop and when I restricted the countries Klarna was not visible:

![Screenshot 2024-09-11 at 14 04 08](https://github.com/user-attachments/assets/7377cc66-068b-4ec0-a12a-08b92f7d29c6)
![Screenshot 2024-09-11 at 14 04 02](https://github.com/user-attachments/assets/19049795-2fdd-44af-bbd2-b570765a6086)



However when I selected all allowed countries then it is visible:

![Screenshot 2024-09-11 at 13 30 33](https://github.com/user-attachments/assets/41d1437e-52b4-4ac1-881b-b3a425cdcafb)
![Screenshot 2024-09-11 at 13 31 24](https://github.com/user-attachments/assets/c27b8497-7791-43c6-bff3-8d51608d98d2)

When you selected "all allowed countries" did you cleared the cache and after that did you check the checkout? If not could you please do this or try incognito mode. If that didn't work could you please send the logs (if this is selected)? You can find them as follows: Molllie > General > Debug & Logging. Here you can easily check the last 100 debug log records. For more records ‘Debug Requests’ needs to be enabled. Or you can check the file that is listed at this place:

```
I've now send them all my log files. Because it's not a caching issue.

**Comment by tropilex** [comment] 2024-09-17 13:48
New update from Klarna support (I send them the info)
------------------

Dear Kees,
 
Thank you for sending the screenshots and the information. There is another customer with the same problem. For now we don't know what is causing the problem as we can't reproduce the problem in our staging environment. In our staging environment it works as intended. 
 
Do you have a staging environment which is exactly the same as your live environment so our developers can check?

I look forward to the information as we really would like to solve this problem.
 
Kind regards,
Angelique

**Comment by Frank-Magmodules** [comment] 2024-09-17 14:10
Hi @tropilex, thanks! We’ll reach out to them and take a look together as well.

**Comment by Frank-Magmodules** [comment] 2024-09-19 06:26
Good morning @tropilex, I understand that this issue was due to a specific Mollie setting on your account, which has now been resolved. Could you please confirm this and close the ticket if everything is in order? Thank you!

**Comment by tropilex** [comment] 2024-09-19 06:42
@Frank-Magmodules Yes it has been fixed this morning!

"We have found out what the problem was. It was nothing related to the integration. It was somehting on our side. You have custom pricing concerning the different Klarna payment methods. This was not adjusted for the payment method Klarna. Therefor you were put on a list so you couldn't use the new Klarna payment method. Yesterday they have fixed this. Now you can use the new payment method Klarna for all your stores."

**Comment by Frank-Magmodules** [comment] 2024-09-19 06:44
That’s fantastic news @tropilex! Thanks for sharing, I’ll go ahead and close this issue now.

**Closed by Frank-Magmodules** 2024-09-19 06:44 UTC
Labels: Question / Issue
