### ISSUE TITLE
URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#462] opened 2021-11-18 10:20 UTC
**Describe the bug**
We face a Magento error in het latest version of your module, that is created a error report. With the following error:

{"0":"URI is not valid and cannot be converted into a string","1":"#1 Laminas\\Http\\Header\\AbstractLocation->getUri() called at [vendor\/laminas\/laminas-http\/src\/Header\/AbstractLocation.php:138]\n#2 Laminas\\Http\\Header\\AbstractLocation->toString() called at [vendor\/laminas\/laminas-http\/src\/PhpEnvironment\/Response.php:114]\n#3 Laminas\\Http\\PhpEnvironment\\Response->sendHeaders() called at [generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php:230]\n#4 Magento\\Framework\\App\\Response\\Http\\Interceptor->sendHeaders() called at [vendor\/laminas\/laminas-http\/src\/PhpEnvironment\/Response.php:144]\n#5 Laminas\\Http\\PhpEnvironment\\Response->send() called at [generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php:248]\n#6 Magento\\Framework\\App\\Response\\Http\\Interceptor->send() called at [vendor\/magento\/framework\/HTTP\/PhpEnvironment\/Response.php:45]\n#7 Magento\\Framework\\HTTP\\PhpEnvironment\\Response->sendResponse() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Framework\\App\\Response\\Http\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#10 Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php:86]\n#11 Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse() called at [vendor\/magento\/framework\/App\/Bootstrap.php:265]\n#12 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/mollie\/checkout\/redirect\/paymentToken\/PAYMENTTOKEN","script_name":"\/index.php","report_id":"c16ab5d11297c3dc53bc2d84110ea42cde4062e63cb72436a01cad847af6d537"}

**Used versions**
- *Magento Version number(eg 2.3.5)*: **2.4.3-p1**
- *Open source/Enterprise/B2b*: **Open source**
- *Mollie version number (Check configuration)*:  **2.3.0**

**Comment by Frank-Magmodules** [comment] 2021-11-22 15:23
HI @JelleGe ,

Thank you for opening this issue. As we can't reproduce this issue, please share the staging/development details of this store using our [contact form](https://www.magmodules.eu/support-form.html) together with the exact steps on how we can reproduce the issue so we can debug this for you.

**Comment by JelleGe** [comment] 2021-11-22 15:57
Hi @Frank-Magmodules,

Thanks! I guess it as something to due with the redirect.
Yes to be sure, we set the module setting "Redirect user when redirect fails" to "Redirect to checkout (payment)".

Maybe this causes the issue?

**Comment by Frank-Magmodules** [comment] 2021-12-17 09:33
HI @JelleGe ,  
  
Do you have some exact steps on how we can reproduce this issue from our end?   
If so, please share this within our [support form](https://www.magmodules.eu/support-form.html) so we can take a look with you.

**Comment by Frank-Magmodules** [comment] 2022-01-07 12:17
Hi @JelleGe ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Comment by RikvdHeijden** [comment] 2023-03-16 15:03
@Frank-Magmodules 
I was investigating this issue for one of our own customers and I think I found the culprit. Just not the reason for it existing.

[This redirect (Controller/Checkout/Redirect.php:137](https://github.com/mollie/magento2/blob/master/Controller/Checkout/Redirect.php#L137)  tries to redirect the redirectUrl filled by the startTransaction call.

This function is documented with the return type mixed. In my case it returns the response of $methodInstance->startTransaction($order).  Which seems to be [this function](https://github.com/mollie/magento2/blob/master/Model/Mollie.php#L249). That function is documented to (and in this case does) return either a boolean or void.

The problem is that neither true, false, or null (or an empty string) are valid values for the setRedirect function. This is what triggers the problem.  

Locally I could prevent the error from occuring by simply redirecting to checkout/cart as seems to happen at other places in the function. But I could not figure out if this is the intented behaviour. Do you have any insight in how this is supposed to work and what the correct fallback URL / flow would be?

**Comment by RikvdHeijden** [comment] 2023-03-28 12:09
@Frank-Magmodules @michielgerritsen 

Any chance I could get a response on my question? If not that's fine too, I'd just like to have some clarity so I know how I can proceed in fixing this issue for my customer.

**Comment by Frank-Magmodules** [comment] 2023-03-28 12:27
HI There @RikvdHeijden Apologies for the delay in responding. I'll reply to you before the weekend!

**Comment by Frank-Magmodules** [comment] 2023-03-31 11:17
Hello @RikvdHeijden,

Do you know the exact scenario when this error occurs? The error is clear but the reason that it occurs is not.  
Thanks!

**Comment by RikvdHeijden** [comment] 2023-04-03 08:29
@Frank-Magmodules 

Sadly I couldn't find a reliable way to reproduce the issue on my end. The error occurred on calls to [store url]/mollie/checkout/redirect/paymentToken/[token]. The issue seemed to happen quite regularly in february and early march, but hasn't been as prevalent since. So it might be connected to a failure in starting the transaction to Mollie, which seems to be wrapped in a retry function. I could share a few of the tokens that resulted in these errors with you, though preferably not in a public issue.

**Comment by Frank-Magmodules** [comment] 2023-05-10 12:51
Hello @RikvdHeijden and @JelleGe, I would like to confirm if this issue is still applicable with the current versions of Magento and Mollie. If it has been resolved, I'm pleased to close it, but I want to make sure we can do so. Please let me know. Thank you.

**Comment by RikvdHeijden** [comment] 2023-05-15 11:14
@Frank-Magmodules Since this issue hasn't happened since early march our customer has put it on-hold on our end and prefers us not to share this information with you at this time. But I'll make sure to loop you guys in asap should the issue resurface. Either way thanks for looking into this!

**Comment by Frank-Magmodules** [comment] 2023-05-15 12:06
Thank you, @RikvdHeijden, for your prompt response on this matter. I understand the client's decision, as the issue seems to be resolved and is no longer relevant. For now, I will proceed to close this matter. However, should a similar issue arise in the future, please feel free to reopen it or create a new issue.

**Closed by Frank-Magmodules** 2023-05-15 12:06 UTC
Labels: Investigating
