### ISSUE TITLE
Enabling Cloudflare will cause payment issues.

### ISSUE THREAD

**Issue by MageShop57** [mollie/magento2#741] opened 2024-02-06 19:41 UTC
**Describe the bug**
I'm getting the payment error when enabling Cloudflare.
Payment status stays on pending or canceled while the customer has paid.

**Comment by fjbender** [comment] 2024-02-07 07:34
Duplicate of #740. Please contact our support team about this. Thanks! :)

**Closed by fjbender** 2024-02-07 07:34 UTC
