### ISSUE TITLE
Order grid has payment option (betaalmethode) column empty

### ISSUE THREAD

**Issue by bamboekeizer** [mollie/magento2#141] opened 2019-05-13 12:28 UTC
Magento version 2.3.1
Mollie version 1.5.2

The order grid column Betaalmethode (payment option) is empty

**Comment by Frank-Magmodules** [comment] 2019-05-14 08:47
Hi @bamboekeizer , Thanks for your message on this, we were able to reproduce this in our own 2.3.1 environment and we are getting this fixed in an upcoming release.

**Comment by Marvin-Magmodules** [comment] 2019-05-29 07:11
Hi @bamboekeizer there seems to be a new condition in Magento 2.3.1 to that checks for active payments, see issue [magento/magento2/issues/22231](https://github.com/magento/magento2/issues/22231). 

We will be implementing a fix in the next release.

**Comment by Marvin-Magmodules** [comment] 2019-05-29 13:52
Hi @bamboekeizer, 

This issue has been reproduced and the fix has been tested, see PR [144](https://github.com/mollie/magento2/pull/144). This will be merged in the upcoming v1.6.1 release. Thank you again for reporting this bug!

**Comment by Marvin-Magmodules** [comment] 2019-06-04 06:05
Hi @bamboekeizer, issue has been resolved in the [v1.6.1](https://github.com/mollie/magento2/releases/tag/v1.6.1) release.
Closing this issue now. Feel free to reopen the issue if this still occurs.

**Closed by Marvin-Magmodules** 2019-06-04 06:05 UTC
Labels: Reproduced & ready for release
