### ISSUE TITLE
Sometimes status of order stays "New" instead of "Pending"

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#114] opened 2019-02-12 18:31 UTC
Sometimes an order status isn't updated to "Pending" (Gaande) but stays "New" (Nieuw) after a succesfull payment is done via Mollie.

This is one of the payments where that happend. But as you can see, the webhook is succesfully called according to the Mollie Dashboard:
![image](https://user-images.githubusercontent.com/17478858/52658900-7a4cca80-2efc-11e9-85f9-e1df88fc3f46.png)

Once the order is shipped, the status is updated to "Finished" (Voltooid).

I'm using plugin version 1.4.7 and Magento 2.2.6. Issue looks like this one: https://github.com/mollie/magento2/issues/79

**Comment by Frank-Magmodules** [comment] 2019-02-13 09:41
Hi @gerben86, can you give us a bit more detailed information about this issue? Is this something that occurs since an update or on specific orders, is this the state in the order itself or only the grid?

Please also check what your logfile shows on this order so we can investigate this. Feel free to contact us directly through our [contact form](https://www.magmodules.eu/contact-us.html).

**Comment by gerben86** [comment] 2019-02-13 10:37
@Frank-Magmodules : I've seen this 2 or 3 times in the last 2 months.
Both the grid and the orderstatus stay "New".

I could mail you the mollie.log for this order so you can see what happened.

**Comment by Frank-Magmodules** [comment] 2019-02-13 12:01
Hi @gerben86 , Yes, please check the logs on these orders as you've got the order-numbers, also please give us as much information as possible about the period and pattern of the problem as this is hard to reproduce.

**Comment by gerben86** [comment] 2019-02-13 12:28
@Frank-Magmodules : This is the 3rd time in a couple of months. So it doesn't happen regularly, I also can't find a pattern.

**Comment by Frank-Magmodules** [comment] 2019-03-12 09:39
Hi @gerben86 , as discussed by email, this issue has not come up since the issue report, so we are closing this issue for now. Please feel free to reopen the issue if you encounter this again and send us the logs so we can investigate.

**Closed by Frank-Magmodules** 2019-03-12 09:39 UTC

**Comment by dbroeders** [comment] 2019-03-17 21:11
I have made a new Shop 2.3.0 and Mollie as payment handler.
Mollie shows status payed - webhook is sent ok
Magento status keeps saying processing -  invoice is not processed.
This is the second payment in a row that fails (both are credit card payments)

**Comment by Frank-Magmodules** [comment] 2019-03-18 07:15
HI  @dbroeders , please sent us your logfile, specific order and store information directly through our [contact form](https://www.magmodules.eu/contact-us.html) so we can investigate this for you.
