### ISSUE TITLE
The required payment token is not available

### ISSUE THREAD

**Issue by b2bdokter** [mollie/magento2#228] opened 2020-03-17 15:57 UTC
After composer update in the mollie.log 

The required payment token is not available

After the checkout customer is redirected to empty cart

**Comment by Frank-Magmodules** [comment] 2020-03-17 16:10
Hi @b2bdokter , thank you for the issue report. Is [static content signing](https://devdocs.magento.com/guides/v2.3/config-guide/cache/static-content-signing.html) enabled in admin as this allows to invalidate the browser cache for static resources?

**Comment by Frank-Magmodules** [comment] 2020-03-25 13:28
Hi @b2bdokter, any update on this issue?

**Comment by b2bdokter** [comment] 2020-04-09 09:17
Hello frank,

Unfortunatly that setting is enabled, and the problem still persist.

**Comment by Frank-Magmodules** [comment] 2020-04-15 13:19
@B2bdokter, as we had the chance to take a look with you this issue was caused by an overwrite on the `view/frontend/web/js/view/payment/method-renderer/default.js` file which has some crucial edits in version 1.11.0. We've now added a warning to the release note to prevent this. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-04-15 13:19 UTC
