### ISSUE TITLE
Surcharge for Klarna not working, causing checkout error 400 and hangs

### ISSUE THREAD

**Issue by tbiest** [mollie/magento2#205] opened 2019-11-16 10:04 UTC
When using the surcharge for Klarna I receive an error 400, the surcharge is not showing and when trying to proceed the user interface hangs.

Mollie version: 1.8.0
Magento version: 2.3.1
Checkout: standard Magento2 (I disabled my one page checkout from Mageplaza just to be sure there is no conflict with a custom checkout)

The error 400 shows up from "set-payment-information" with a response " Verzoek komt niet overeen met een route." (EN: "Request does not match a route")

**Comment by Frank-Magmodules** [comment] 2019-11-18 07:40
Hi @tbiest ,

Thanks you for your message. I can't reproduce this on a vanilla Magento 2.3.1 with Mollie 1.8.0. 
Can you sent us some server/back-end details through our [contact form](https://www.magmodules.eu/contact-us.html) so we can take a look with you? It could be a conflict with the Mageplaza checkout files but surely we would be happy to take a look with you. 

Thanks!

**Comment by tbiest** [comment] 2019-11-18 18:11
Hi Frank, I have send you the backend details. Thank you for the help.

**Comment by Frank-Magmodules** [comment] 2019-12-03 15:25
Hi @tbiest, thanks again for detailed issue report. The issue has been resolved in the [v1.9.0](https://github.com/mollie/magento2/releases/tag/v1.9.0) release. 
We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2019-12-03 15:25 UTC

**Comment by tbiest** [comment] 2019-12-03 19:56
Hi @Frank-Magmodules the Fee is visible and order no longer 'hangs'.

I do have one remark: it seems the Tax for the Payment Fee is not saved correctly: it is included in the total price but not in the Tax specification (only the product's taxes are shown in the breakdown). Also, the tax details are not stored in the backend so that tax reports are incomplete (I am missing the tax, when you do a quarterly tax calculation using the tax report you are missing taxes)

**Comment by Frank-Magmodules** [comment] 2019-12-05 12:09
HI @tbiest , great the fee is working now. I've reproduced your remark on the missing TAX from the reports and created an internal-issue for this, thank you for sharing this. The issue will be fixed in an upcoming release.
