### ISSUE TITLE
Payment status remains open when in fact it should be paid

### ISSUE THREAD

**Issue by ThomasMW** [mollie/magento2#615] opened 2023-02-14 16:23 UTC
**Describe the bug**
We are noticing quite a few orders where the payment status remains 'Open' even though the order was actually fully paid. Only after retrieving the payment status manually using the 'Fetch Status' button the payment status is set to 'Paid'. This creates a problem because the order is never set to processing and is not sent to our fulfillment party.

**Used versions**
- Magento 2.4.2-p2
- Open Source
- Mollie v2.21.1

**Expected behavior**
After the customer pays the payment status should be set to 'Paid' so the order is set to 'Processing'.

**Actual behavior**
The payment status remains open and the order is never processed and eventually canceled.

**Additional context**
We only seem to have this issue when people use iDeal or Bancontact as a payment method.

**Comment by Frank-Magmodules** [comment] 2023-02-15 09:10
HI @ThomasMW , thank you for opening this issue, it seems we can't directly reproduce this issue.

Can you please share the log files together with a screenshot of the webhook flow on these orders from the Mollie dashboard through our [contact form](https://www.magmodules.eu/support-form.html) so we can check together what's happening on these orders?

Thanks!

**Comment by dverkade** [comment] 2023-02-15 09:39
@ThomasMW @Frank-Magmodules Having same issues here as well. Webhook in Mollie says succesfull. In the transactions tab the payment seems succesfull as well, but on the order overview screen it still says "open".

**Comment by Frank-Magmodules** [comment] 2023-02-15 09:42
HI @dverkade , can you [contact us directly](https://www.magmodules.eu/support-form.html) as well so we can take a look into this?   
As this seems like a Webhook issue which makes it a bit hard to reproduce.

**Comment by Medeka** [comment] 2023-02-16 08:50
Hello @Frank-Magmodules, we have the same issues since we updated Mollie to the latest version on Magento 2.4.5-p1. We shared all details with Mollie twice. It happens in about 10 percent of orders.

**Comment by jesse-deboer** [comment] 2023-02-16 12:04
We are also experiencing this issue, we are running the following:
PHP8.1 and Magento 2.4.5-p1

After updating Mollie from **2.20.0 to 2.20.1** this problem started to happen. When we downgraded the problem went away.

The notitications about the captured amount do show up, but the payment status is never updating which leaves the orders open while the payment is made and shown in the notifications

**Comment by Quazz** [comment] 2023-02-16 12:10
As far as I can tell, in certain cases the 'sales_order_payment' table does not get updated correctly, thus making the backend report back incorrectly.

Mollie uses the "additional_information" field in particular for its display on an order.

What further complicates this is that the "fetch status" button compares the order state on Magento with the Mollie order state. If they match, it won't update.

So we can have an order in "processing" on both Mollie and Magento, but the additional_information field claims "created" for the payment only, despite the payment being processed fully otherwise as can be observed on Mollie dashboard.

**Comment by Medeka** [comment] 2023-02-16 12:26
Yes in these cases the 'sales_order_payment' table has not been updated, even though an invoice has been created. The 'invoice' button also remains active so we can book the same invoice twice.

**Comment by Frank-Magmodules** [comment] 2023-02-16 13:32
Thank you for opening up and for the input on this issue. It appears that the issue may be linked to changes in the default webhook response and/or the timing of that response. We are aware of this issue, but reproducing it has proven difficult. To ensure the effectiveness of our solution, we must conduct secure testing. 

Still, it would be helpful if you could share the log files with us through our [contact form](https://www.magmodules.eu/support-form.html) so we can double-check the connection of the issue. We will provide an update shortly. Thank you for your valuable feedback thus far.

**Comment by Frank-Magmodules** [comment] 2023-02-16 14:19
> @Frank-Magmodules do you have an email? That form has a low filesize limit.

Sure @gjportegies , it's frank\[AT\]magmodules.eu

**Comment by jorgb90** [comment] 2023-02-17 10:20
Same issue here!

**Comment by ThomasMW** [comment] 2023-02-17 13:28
> Still, it would be helpful if you could share the log files with us through our [contact form](https://www.magmodules.eu/support-form.html) so we can double-check the connection of the issue. We will provide an update shortly. Thank you for your valuable feedback thus far.

Sure thing, I submitted a sample of 5 orders through the contact form.

**Comment by peterjaap** [comment] 2023-02-17 13:30
Same issue here!

**Comment by Frank-Magmodules** [comment] 2023-02-17 13:31
Received it @ThomasMW , thanks!

**Comment by jesse-deboer** [comment] 2023-02-20 11:49
@Frank-Magmodules the solution for now if you are facing this issue is to temporarily downgrade to [v2.20.0](https://github.com/mollie/magento2/releases/tag/v2.20.0) right?

**Comment by Frank-Magmodules** [comment] 2023-02-21 18:50
Thank you all for bringing this to our attention. Based on our investigation, it appears that the issue is related to the webhook firing faster than before, which results in an update before the order is saved into Magento. To address this, we have implemented a solution that involves appending an encrypted order ID to the webhook URL. This will serve as a fallback in situations where the transaction ID is not found in Magento.

In such cases, we will compare the order ID from the metadata in the loaded transaction on the Mollie side and set the transaction ID to the order to process the webhook. This will ensure that the order is properly processed and any necessary actions are taken. This solution is now available within our new [2.22.0](https://github.com/mollie/magento2/releases/tag/v2.22.0) release.

We understand the importance of timely and accurate order processing and appreciate your patience as we work to resolve this issue. Please let us know if you have any further questions or concerns.

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2023-02-21 18:50 UTC
Labels: Investigating
