### ISSUE TITLE
[ISSUE] Creating a payment link without selected methods triggers an error.

### ISSUE THREAD

**Issue by qsolutions-pl** [mollie/magento2#725] opened 2023-12-05 17:11 UTC
**To Reproduce**
1. Go to 'Admin Panel'
2. Click on 'Create Order'
3. Fill some client data / use guest data
4. Add some products
5. Fill Address Data
6. Use Mollie: Payment Link as a payment option:
7. Do not select ANY options:
![image](https://github.com/mollie/magento2/assets/4256191/9f15aefa-2614-4ed8-89fc-c48746dc4a73)

**Expected behavior**
Order id created

**Actual behavior**
Fatal error is thrown

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment] 2023-12-06 09:55
HI There @qsolutions-pl ,

Thank you for raising this issue. It appears to be a duplicate of [an earlier ticket](https://github.com/mollie/magento2/issues/718#issuecomment-1824049927), so let me share the response with you:

> We investigated the error you're experiencing and found that it occurs when no payment methods are selected in the multiple-select field designed to limit method options. To temporarily resolve the issue, please select some payment methods to proceed or apply [this](https://gist.github.com/Frank-Magmodules/3b908b149c1032bdcbcad9c67bb35929#file-gistfile1-diff) patch file. Surely, we will include this fix in our upcoming release!

I will keep the issue open until we've implemented the fix in the upcoming release. Thank you for your patience on that!

**Comment by qsolutions-pl** [comment] 2023-12-06 10:51
This is causing problem in all our projects, can't this just be merged as a hotfix ?

**Comment by Frank-Magmodules** [comment] 2024-01-22 15:36
Appreciate your patience, @qsolutions-pl! Exciting news – we've just rolled out version [2.33.0](https://github.com/mollie/magento2/releases/tag/v2.33.0), including the necessary fix. Additionally, we've refactored the functionality of Payment links; details can be found in [this comment](https://github.com/mollie/magento2/issues/718#issuecomment-1904260656). Thanks once more; closing this issue now.

**Closed by Frank-Magmodules** 2024-01-22 15:36 UTC
Labels: Reproduced & ready for release, Investigating
