### ISSUE TITLE
[Amasty Extra Fee] Klarna payment with GBP and Amasty Extra Fee 422 Error

### ISSUE THREAD

**Issue by Ahmet-Djedovic** [mollie/magento2#576] opened 2022-10-25 09:52 UTC
**Describe the bug**
The moment a customer try to place an order with a Amasty Extra Fee item on the a storeview with sterling pounds, then choose Klarna, we get an error message and the customer can't continue with checkout.

**Used versions**
- *Magento Version number*: **2.4.3-p1**
- *Open source/Enterprise/B2b*: **Open source**
- *Mollie version number*: **v2.17.0**

**To Reproduce**
1. Go to admin panel and create a Fee this example fee:
![image](https://user-images.githubusercontent.com/62017184/197738014-22cc6de1-95c7-4788-9f91-e8999eb3413a.png)

2. Go to frontend side and select a storeview with GBP:
![image](https://user-images.githubusercontent.com/62017184/197740666-b5627ef4-8786-453f-a90b-03616f8db798.png)

3. Proceed to the checkout section and fill in Netherlands as a billing and shipping adress:
4. Select a your fee that you have created in step 1
![image](https://user-images.githubusercontent.com/62017184/197740905-8c7875a9-d2c9-4668-a698-78d3c265734a.png)

5. Select Klarna Pay Later as a payment method:
![image](https://user-images.githubusercontent.com/62017184/197741415-bee1f87e-b4f0-4fa6-85d2-fca0547a51b8.png)

6. Proceed to finish checkout and see error:
![image](https://user-images.githubusercontent.com/62017184/197741752-e0bc5842-72d4-4afa-a30e-e0bcb9a1fed1.png)

**Expected behavior**
As a user of i would like to be able to buy a product using mollie with a extra fee with my preferred payment method (klarna) and preferred currency (GBP) 

**Actual behavior**
Expetion gets thrown when i try to pay for my goods:

`
[2022-10-25T09:46:42+0000] Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €220.37 but got €220.42. Field: amount. Documentation: https://docs.mollie.com/overview/handling-errors
`

**Screenshots**
![image](https://user-images.githubusercontent.com/62017184/197742544-60ee4da5-c304-4fba-ba4f-f9641f046569.png)

**Additional context**
Please make the fee above the ~0.30, 0.25 does work. Any amount higher then 0.30 cent wont work

**Comment by Frank-Magmodules** [comment] 2022-11-22 07:59
Hi @Ahmet-Djedovic , thank you for opening this issue, and sorry for the late response. We've tried to find the plugin that you are using to reproduce the issue but didn't succeed. Can you please [contact us](https://www.magmodules.eu/support-form.html) directly so we can take a look with you? Thanks a lot!

**Comment by Frank-Magmodules** [comment] 2023-01-12 19:11
Hi @Ahmet-Djedovic,

Due to the lack of information and we can’t reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2023-01-12 19:11 UTC
Labels: enhancement, Investigating
