### ISSUE TITLE
Incompatibility with Amazon Pay

### ISSUE THREAD

**Issue by KathiD303** [mollie/magento2#817] opened 2024-09-19 09:13 UTC
**Describe the bug**
When choosing a Mollie payment in payment methods and then deciding to complete checkout with Amazon Pay (option "Amazon Pay in final checkout step" in Amazon Pay module enabled) the checkout fails with: 

[2024-09-19T08:50:09.892439+00:00] amazonClientLogger.INFO: Quote is already associated with an order. QuoteId: 211 OrderIds: B000000073 [] []
[2024-09-19T08:50:09.894330+00:00] amazonClientLogger.ERROR: Unable to complete Amazon Pay checkout. Can't submit quote id: 211 [] []
[2024-09-19T08:50:09.894392+00:00] amazonClientLogger.ERROR: Unable to complete Amazon Pay checkout Unable to complete Amazon Pay checkout [] []

**Used versions**
- *Magento Version number: 2.4.5-p9
- *Open source/Enterprise/B2b*: Commerce Cloud
- *Mollie version number (Check configuration)*: 2.40.1

**To Reproduce**
1. Use any Mollie payment method in checkout
2. Cancel the payment by going back to cart
3. Try to checkout with Amazon Pay

**Expected behavior**
Amazon checkout should be completed.

**Actual behavior**
Amazon checkout fails.

**Screenshots**
Screencast: https://go.screenpal.com/watch/cZj3QwV976L

**Comment by Frank-Magmodules** [comment] 2024-09-19 09:42
Hi There @KathiD303 ,

Thank you for raising this issue. It seems that the problem is caused by the Amazon payment module itself rather than the Mollie plugin. I suggest opening a ticket with Amazon so they can investigate the issue first. For now, I’ll close this ticket until we have more information indicating that the Mollie plugin is responsible. Thank you for your understanding!

**Closed by Frank-Magmodules** 2024-09-19 09:42 UTC
