### ISSUE TITLE
Mollie Payment link not send with coupon active

### ISSUE THREAD

**Issue by Goeny** [mollie/magento2#140] opened 2019-05-10 15:21 UTC
When the Mollie Payment Link from the admin section is selected, the link will not be available to customers when a coupon is used.

Can be recreated.

- Create order from admin
- Select product(s)
- add couponcode and activate
- select shipping method
- Select Mollie Payment Link (I used iDEAL)
- Create order

The email will be send and payment method is correct, however.. the link is not provided in email or PDF.

**Comment by Frank-Magmodules** [comment] 2019-05-14 09:06
Hi @Goeny ,

Thanks for your message on this, we were not able to reproduce this in our own environment. Which version of the Mollie and Magento version are you using?

**Comment by Goeny** [comment] 2019-05-14 09:16
Magento 2.3.0
Mollie 1.4.7

**Comment by Frank-Magmodules** [comment] 2019-05-14 10:44
Hi @Goeny ,

Thanks, can you make sure that you are also running into this problem when using the latest Mollie version?

**Comment by Goeny** [comment] 2019-05-14 11:02
According to my install, there is no update available...

Checked using web extension manager and composer... something wrong with my install??

**Comment by Frank-Magmodules** [comment] 2019-05-14 11:58
HI @Goeny ,

You can update to 1.5.2 by running: "composer require mollie/magento2 1.5.2"

**Comment by Goeny** [comment] 2019-05-14 13:13
Mollie updated to 1.5.2
Unfortunately still not working.

When trying to save the order now, i get a new error:
`Fout tijdens opslaan van order: Class Vertex\Tax\Model\Api\Data\InvoiceRequestBuilder\GiftWrapProcessor does not exist`

If i submit a few times again, the error above goes away and the order is saved. The link is still not send though.

**Comment by Frank-Magmodules** [comment] 2019-05-15 06:55
HI @Goeny , 

Seems we can't reproduce this, can you please fill in our [contact form](https://www.magmodules.eu/contact-us.html) and share your login details so we can take a look with you? 

Thanks!

**Comment by Goeny** [comment] 2019-05-15 07:28
Done...

**Comment by Frank-Magmodules** [comment] 2019-06-24 12:17
Hi @Goeny , This issue has been reproduced and we are working on a fix. This fix will be part of the the upcoming v1.6.3 release. Thank you again for reporting this bug!

**Comment by Frank-Magmodules** [comment] 2019-07-19 11:30
Hi @Goeny. 

We have just released te new version [v1.6.4](https://github.com/mollie/magento2/releases/tag/v1.6.4) that fixes this issue.
Thank you of the input and patience. Closing this issue now but please feel free to reopen the issue if this problem still occurs.

**Closed by Frank-Magmodules** 2019-07-19 11:30 UTC

**Comment by Goeny** [comment] 2020-01-17 19:19
Hi @Frank-Magmodules 

Unfortunately the problem still occurs when adding a coupon to an order with bundle products in it.

How it should be... (This is with Simple products only)
![Screenshot_12](https://user-images.githubusercontent.com/3872395/72639697-7922e980-3966-11ea-9221-9a6d488bfe14.png)

How it is (With Bundle products in order)
![Screenshot_13](https://user-images.githubusercontent.com/3872395/72639736-948df480-3966-11ea-9bad-635e39778722.png)

**Comment by Frank-Magmodules** [comment] 2020-01-21 09:02
HI @Goeny , Thank you for commenting on this issue. It seems i have reproduced this issue and we will implement a fix for this issue in upcoming release!

**Comment by ginos87** [comment] 2021-02-10 12:49
Hi @Frank-Magmodules has this been fixed in the latest update? We are currently on 1.12.2 and are experiencing the same problem

![Screenshot 2021-02-10 at 13 41 13](https://user-images.githubusercontent.com/16663890/107512171-bc21b180-6ba6-11eb-9b57-2dc26fd7daaf.png)

**Comment by Frank-Magmodules** [comment] 2021-02-10 12:51
HI @ginos87 ,  Yes, this is fixed in the latest version!

**Comment by ginos87** [comment] 2021-02-10 13:09
@Frank-Magmodules oh wait, I didn’t see that the issue was with an active coupon. 

Our client does not use coupons when making an order in the admin. Yet when a customer receives a mail the same problem occurs with an empty link
