### ISSUE TITLE
Mollie Second Chance email is send twice

### ISSUE THREAD

**Issue by gjportegies** [mollie/magento2#429] opened 2021-09-09 14:26 UTC
**Describe the bug**
The second chance email is send twice. There are some minutes in between the mails that are sent. 

**Used versions**
- Magento 2.4.3
- Open source
- 1.30.0

**Expected behavior**
The second chance email is send once.

**Actual behavior**
The second chance email is send twice.

**Screenshots**
![mollie-second-chance](https://user-images.githubusercontent.com/6707410/132704341-3f463b79-ac99-462c-b488-deeb767e65b5.png)

**Additional context**

```
[2021-09-09 08:40:02] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053783 [] []
[2021-09-09 08:40:02] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053783 [] []
[2021-09-09 08:40:02] Mollie.INFO: info: Sending second chance email for order #6000053783 [] []
[2021-09-09 08:40:03] Mollie.INFO: info: Second chance email for order #6000053783 sent [] []
[2021-09-09 08:45:04] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053783 [] []
[2021-09-09 08:45:04] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053783 [] []
[2021-09-09 08:45:04] Mollie.INFO: info: Sending second chance email for order #6000053783 [] []
[2021-09-09 08:45:05] Mollie.INFO: info: Second chance email for order #6000053783 sent [] []
[2021-09-09 08:50:03] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053785 [] []
[2021-09-09 08:50:03] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053785 [] []
[2021-09-09 08:50:03] Mollie.INFO: info: Sending second chance email for order #6000053785 [] []
[2021-09-09 08:50:05] Mollie.INFO: info: Second chance email for order #6000053785 sent [] []
[2021-09-09 08:55:03] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053785 [] []
[2021-09-09 08:55:03] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053785 [] []
[2021-09-09 08:55:03] Mollie.INFO: info: Sending second chance email for order #6000053785 [] []
[2021-09-09 08:55:04] Mollie.INFO: info: Second chance email for order #6000053785 sent [] []
```

```
[2021-09-09 11:20:03] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053787 [] []
[2021-09-09 11:20:03] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053787 [] []
[2021-09-09 11:20:03] Mollie.INFO: info: Sending second chance email for order #6000053787 [] []
[2021-09-09 11:20:04] Mollie.INFO: info: Second chance email for order #6000053787 sent [] []
[2021-09-09 11:20:04] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053783-1 [] []
[2021-09-09 11:20:04] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053783-1 [] []
[2021-09-09 11:20:04] Mollie.INFO: info: Sending second chance email for order #6000053783-1 [] []
[2021-09-09 11:20:04] Mollie.INFO: info: Second chance email for order #6000053783-1 sent [] []
[2021-09-09 11:25:03] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053787 [] []
[2021-09-09 11:25:03] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053787 [] []
[2021-09-09 11:25:03] Mollie.INFO: info: Sending second chance email for order #6000053787 [] []
[2021-09-09 11:25:04] Mollie.INFO: info: Second chance email for order #6000053787 sent [] []
[2021-09-09 11:25:04] Mollie.INFO: info: Preparing to send the payment reminder for order #6000053783-1 [] []
[2021-09-09 11:25:04] Mollie.INFO: info: Payment reminder record moved to sent table for order #6000053783-1 [] []
[2021-09-09 11:25:04] Mollie.INFO: info: Sending second chance email for order #6000053783-1 [] []
[2021-09-09 11:25:04] Mollie.INFO: info: Second chance email for order #6000053783-1 sent [] []
```

**Comment by Frank-Magmodules** [comment] 2021-09-27 12:07
HI @gjportegies , thank you for opening this issue, it seems that we can't reproduce this issue directly but it seems there is breaking something during the saving process. Can you find more information about this issue in other log files? If possible, please share login details and/or the other relevant logfiles using our [contact form](https://www.magmodules.eu/support-form.html)?

Thank you!

**Comment by Frank-Magmodules** [comment] 2021-11-09 10:56
HI @gjportegies ,

We didn't receive any response on this issue anymore, therefore, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our \[contact form \](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2021-11-09 10:56 UTC
Labels: Investigating
