### ISSUE TITLE
Cancellation issue 

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#187] opened 2019-08-06 07:20 UTC
Hi,

When looking in the Mollie dashboard I saw an Apple Pay payment webhook failing:

Aanroepen webhook mislukt (Got HTTP/1.1 503 Service Unavailable instead of 20x)

I tried to fetch this order in Magento manually, but also receiving an error there:

![Schermafbeelding 2019-08-06 om 09 16 25](https://user-images.githubusercontent.com/7294081/62519148-51621e00-b82b-11e9-9cb6-7e5db426bdf9.png)

**Comment by jorgb90** [comment] 2019-08-07 09:22
Mm seems to be not only Apple Pay other expired transactions also have this issue, also spread over all our shops.

**Comment by Frank-Magmodules** [comment] 2019-08-07 09:28
Hi @jorgb90 , Thank you for your message on this. As we can't reproduce this issue, could you contact us via our [contact form](https://www.magmodules.eu/contact-us.html )?  Through e-mail we can exchange logfiles and specific data outside of Github to locate the problem.

**Comment by jorgb90** [comment] 2019-08-07 09:32
@Frank-Magmodules Sure

**Comment by jorgb90** [comment] 2019-08-07 10:02
@Frank-Magmodules Send an email, but somehow all transactions which failed in our shops started working now by fetching them.. Could it be that its solved by re-saving the Mollie settings? I was doing this because of enabling mollie.log or did a change at Mollie's occur?

**Comment by jorgb90** [comment] 2019-08-07 10:07
@Frank-Magmodules Mm nevermind.. It's just really strange behaviour now a new order is again getting the failed webhook call.

![Schermafbeelding 2019-08-07 om 12 06 25](https://user-images.githubusercontent.com/7294081/62614543-f2c0a100-b90b-11e9-863b-c6228d83f6c8.png)

**Comment by jorgb90** [comment] 2019-08-07 11:31
@Frank-Magmodules Found out that fetching is working when order is cancelled first in Magento, as long as its in Pending Payment it doesn't.

**Comment by Frank-Magmodules** [comment] 2019-08-09 10:53
Hi @jorgb90, thanks again for detailed issue report. The issue has been resolved in the [v1.7.0](https://github.com/mollie/magento2/releases/tag/v1.7.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2019-08-09 10:53 UTC
