### ISSUE TITLE
Surcharge is applied to the grand total but when the order is paid, Magento says the customer has to pay the surcharge (amount left)

### ISSUE THREAD

**Issue by erwinschaap** [mollie/magento2#518] opened 2022-04-22 11:35 UTC
**Describe the bug**
This morning a customer paid via PayPal. We ask for a fee of 3% (configured). The customer for the entire amount but the order states that the customer has to pay the 3% fee.

Total Paid: for example: 100 euro
Grand total : 103 euro
In the Mollie logs: 103 euro
Total due: 3 euro

**Used versions**
Magento 2.4.3 Open Source 
Mollie version: v2.6.0

**To Reproduce**
1. Choose Paypal as payment method
2. Add 3% surcharge
3. There is a paid order and the total paid is not the same as in the mollie logs / grand total

**Expected behavior**
The customer does not have to pay extra surchage because it's already paid. There is no total due.

**Actual behavior**
There is a total due of the total surcharge costs

**Screenshots**
![image](https://user-images.githubusercontent.com/32191830/164706915-6a0c315a-a3a0-4db3-b8d2-13a36d87b47a.png)
![image](https://user-images.githubusercontent.com/32191830/164706955-fe9a5f8f-cb7d-4a1c-bfc6-4c43a40f87ac.png)

**Additional context**
No addition context

**Comment by Frank-Magmodules** [comment] 2022-04-25 07:07
HI @erwinschaap , I just tried to reproduce this but I can't break it on the latest Mollie release. 

As we did some changes regarding the payment fees and the order processing in the latest release, can you please update the plugin to the latest version and try to reproduce this again?

![](https://user-images.githubusercontent.com/24823946/165037463-4add9285-4267-4a6b-9646-bfd88d7a3488.png)

**Comment by erwinschaap** [comment] 2022-04-26 06:53
@Frank-Magmodules Could you update the official plugin on the Magento Marketplace? It is outdated

**Comment by Frank-Magmodules** [comment] 2022-04-28 06:32
HI @erwinschaap , the latest version is there now!
https://marketplace.magento.com/mollie-magento2.html

**Comment by erwinschaap** [comment] 2022-04-29 06:50
@Frank-Magmodules We updated the module today but the fee is sometimes good but mostly not. (See screenshot)
The following information in the request is not correct. You can see the mollie fee is zero but the grand total differs with subtotal. 
In this case the mollie payment fee should be 4,50 euro

![image](https://user-images.githubusercontent.com/32191830/165896934-05782b8f-620b-4710-8a1c-2ea810c272d5.png)

**Comment by dennisvanderweide** [comment] 2022-04-29 08:01
I fixed it by saving the `Quote` after setting the Mollie payment fee in `Mollie\Payment\Model\PaymentFee\Quote\Address\Total\PaymentFee::collect` and `Mollie\Payment\Model\PaymentFee\Quote\Address\Total\PaymentFeeTax::collect`

``` PHP
/**
     * @param Quote $quote
     * @param ShippingAssignmentInterface $shippingAssignment
     * @param Total $total
     * @return $this|AbstractTotal
     */
    public function collect(Quote $quote, ShippingAssignmentInterface $shippingAssignment, Total $total)
    {
        ...

        $attributes->setMolliePaymentFee($amount);
        $attributes->setBaseMolliePaymentFee($result->getRoundedAmount());

        $this->quoteResourceModel->save($quote);
        return $this;
    }
```

**Comment by jorgb90** [comment] 2022-05-18 08:25
@dennisvanderweide Can you help us to add this correctly without getting a "main.CRITICAL: Exception: Notice: Undefined property: Mollie\Payment\Model\PaymentFee\Quote\Address\Total\PaymentFee::$quoteResourceModel" ?

**Comment by Frank-Magmodules** [comment] 2022-06-23 13:02
Hi All,

Saving the quote in the totals should not be required. If every total saves the quote the whole checkout will get slow easily. Most likely, something prevents the quote from being saved after the totals are processed. 

Would it be possible to provide [us](https://www.magmodules.eu/support-form.html) with access to your environment so we can investigate this more?

**Comment by Frank-Magmodules** [comment] 2022-08-05 09:10
HI @erwinschaap ,

Due to the lack of information and the fact that we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form ](https://www.magmodules.eu/support-form.html)so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-08-05 09:10 UTC
Labels: Investigating
