### ISSUE TITLE
Issue with Onestepcheckout and first load and changes payment method

### ISSUE THREAD

**Issue by JoostWan** [mollie/magento2#427] opened 2021-09-06 12:22 UTC
**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.5
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.17.0

**To Reproduce**
1. Add products in cart
2. Go to checkout (onestepcheckout.com)
3. Check the browser console log

**Expected behavior**
No error about payment information

**Actual behavior**
There is a error message. One pageload Onestepcheckout selects in our case iDeal als default payment method. In the code from Mollie when a payment method is changed there is a call to set-payment-information. In the case a guest checks out there is no e-mailaddress available on page load so there well be an error. This wil be no error in default checkout because payment method is a different step in the checkout flow. But on OSC everything is at one page. 

https://github.com/mollie/magento2/blob/master/view/frontend/web/js/view/checkout/save-payment-method.js#L33

Maybe this is the fix? For me it's working. 

```
                if (resourceUrlManager.getCheckoutMethod() === 'guest') {
                    if (!quote.guestEmail) {
                        return;
                    }
                }

```

**Comment by Frank-Magmodules** [comment] 2021-09-07 10:52
HI @JoostWan ,

Thank you for opening this issue, the Mollie Plugin version that you are using is over a year old and a lot of things _(also front-end related)_ have changed. Can you please check if you still have this issue on the latest version? Thanks!

**Comment by Frank-Magmodules** [comment] 2021-09-29 08:24
Hi @JoostWan ,

Can you please let me know if the plugin update did fixes your problem?

**Comment by JoostWan** [comment] 2021-09-29 09:21
@Frank-Magmodules Not yet but the file that's created the calls is not changed in later versions. But it's working fine at our side with some extra checks in javascript.

**Comment by Frank-Magmodules** [comment] 2021-11-09 10:58
HI @JoostWan ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2021-11-09 10:58 UTC
Labels: Investigating
