### ISSUE TITLE
Klarna invoice on autorise will set shipped orders to closed instead of complete

### ISSUE THREAD

**Issue by henkvalk** [mollie/magento2#466] opened 2021-11-30 15:02 UTC
**Describe the bug**

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.28.0

**To Reproduce**
1. Go to 'Stores > Settings - Configuration > Mollie > Advanced'
2. Click on 'Triggers & Languages'
3. **When to create the invoice**? set to `On Authorize` 
4. Customer create order with Klarna
5. _Order must be authorized by Klarna_
6. Order is set to Processing
7. Ship order

**Expected behavior**
- The invoice is created and set as paid
- After shipping the order will set to Complete

**Actual behavior**
A clear and concise description of what actually happens.
- The invoice is created, but not set to paid
- After shipping the order will set to Closed

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment] 2021-12-06 09:19
HI @henkvalk ,

Thank you for opening this issue, it seems that your Mollie version is quite outdated and as we can't reproduce this issue in the latest version, I would recommend updating the plugin to the latest [version](https://github.com/mollie/magento2/releases) as that should fix your issue. We are closing this issue now but please feel free to reopen the issue if you have any other comments or questions regarding this issue.

**Closed by Frank-Magmodules** 2021-12-06 09:19 UTC
