### ISSUE TITLE
Set order for existing transactions not allowed

### ISSUE THREAD

**Issue by niekappartmedia** [mollie/magento2#533] opened 2022-06-20 09:03 UTC
**Describe the bug**
We move from payment API to order API because the use of the second chance email.
When creating shipments for multiple orders we get the error message above: "Set order for existing transactions not allowed"

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: V2.12.0

**To Reproduce**
1. Go to orders
2. Select orders you want to ship made with order api for mollie
3. Click/select ship from the bulk actions
4. See error "Set order for existing transactions not allowed"

**Expected behavior**
We don't expect this error to see.

**Actual behavior**
Shows error: "Set order for existing transactions not allowed"

**Screenshots**
![image](https://user-images.githubusercontent.com/56023375/174566212-2ff521e8-417e-4ff1-b237-4e53595cb1e6.png)

**Additional context**

**Comment by Frank-Magmodules** [comment] 2022-07-21 07:11
HI @niekappartmedia , 

Do you still need help on this issue? 
Please share more information once you have or close the issue if you don't need help anymore.

**Comment by Frank-Magmodules** [comment] 2022-08-01 06:38
Hi @niekappartmedia ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-08-01 06:38 UTC
Labels: question
