### ISSUE TITLE
main.CRITICAL: Exception message: Kon de orderregels niet opslaan. Fout: SKU’s komen niet overeen

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#577] opened 2022-11-01 12:30 UTC
After some module updates we are having the following error. For us a rather strange one?

[2022-11-01T12:09:17.442833+00:00] main.CRITICAL: Exception message: Kon de orderregels niet opslaan. Fout: SKU’s komen niet overeen
Trace: <pre>#1 Mollie\Payment\Model\Mollie->startTransaction() called at [vendor/mollie/magento2/Controller/Checkout/Redirect.php:240]
#2 Mollie\Payment\Controller\Checkout\Redirect->startTransaction() called at [vendor/mollie/magento2/Controller/Checkout/Redirect.php:127]
#3 Mollie\Payment\Controller\Checkout\Redirect->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#4 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#5 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#6 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->___callPlugins() called at [generated/code/Mollie/Payment/Controller/Checkout/Redirect/Interceptor.php:23]
#7 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#8 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->___callPlugins() called at [generated/code/Mollie/Payment/Controller/Checkout/Redirect/Interceptor.php:32]
#12 Mollie\Payment\Controller\Checkout\Redirect\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:245]
#13 Magento\Framework\App\FrontController->getActionResponse() called at [vendor/magento/framework/App/FrontController.php:212]
#14 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:147]
#15 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#16 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#17 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#18 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/mirasvit/module-push-notification/src/PushNotification/Plugin/Framework/App/FrontController/FirebaseServerWorkerJsResponsePlugin.php:74]
#20 Mirasvit\PushNotification\Plugin\Framework\App\FrontController\FirebaseServerWorkerJsResponsePlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/mirasvit/module-cache-warmer/src/CacheWarmer/Plugin/Debug/OnHitPlugin.php:145]
#22 Mirasvit\CacheWarmer\Plugin\Debug\OnHitPlugin->aroundAroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->___callPlugins() called at [generated/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin/Interceptor.php:23]
#25 Magento\PageCache\Model\App\FrontController\BuiltinPlugin\Interceptor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#26 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#27 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#28 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#29 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#30 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#31 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre> [] []

**Comment by Frank-Magmodules** [comment] 2022-11-03 12:07
Thank you for opening this issue! Based on the current information we can't see directly why this is happening. Therefore, can you please share more details of this environment with us through our secured [contact form](https://www.magmodules.eu/support-form.html)? Thanks a lot!

**Comment by Frank-Magmodules** [comment] 2022-11-14 07:59
Hi @jorgb90 ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-11-14 07:59 UTC
Labels: question, Investigating
