### ISSUE TITLE
Virtual order automatically set to complete

### ISSUE THREAD

**Issue by hansvereyken** [mollie/magento2#583] opened 2022-11-11 09:57 UTC
**Describe the bug**
When placing a virtual order (none of the items requires shipment (eg: virtual gift cards)), the order status is set to complete instead of the status configured in Stores -> Settings -> Configuration -> Mollie -> Advanced -> Statuses -> Status Processing

**Used versions**
- *Magento Commerce (Adobe Commerce)  2.4.5-p1*:
- *Mollie 2.13.0*:
- *PHP 8.1*

**To Reproduce**
1. Place an order only containing virtual products
2. Go through the checkout, pay for the order
3. Go to the admin, check the newly created order status

**Expected behavior**
The status is set to the status configured in Stores -> Settings -> Configuration -> Mollie -> Advanced -> Statuses -> Status Processing

**Actual behavior**
The order is set to 'complete'

**Additional context**
This probably is Magento's doing, since no shipping is required, it will set it to complete automatically. But this is a problem for our bookkeeping integration.

**Comment by hansvereyken** [comment] 2022-11-11 10:00
https://github.com/magento/magento2/issues/3922

**Comment by Marvin-Magmodules** [comment] 2022-11-11 10:32
Hi @hansvereyken, this is intended behavior as these orders do not require a shipment and thus do not touch the processing state. A processing state holds orders that have an invoice and still require a (full)shipment. So setting a processing status does not apply to these orders.

**Comment by hansvereyken** [comment] 2022-11-11 10:56
Yes, that's what I expected. As mentioned, this is a problem for our bookkeeping integration, it will only process 'processing' orders. The virtual orders never reach this state. According to Magento's documentation, it's the payment module setting the after-payment-order-status, apparently this excludes virtual orders (not documented as far as I can see).

**Comment by Marvin-Magmodules** [comment] 2022-11-14 12:56
Hi @hansvereyken, yes indeed. We are closing this issue now as this behavior is as intended and also not an issue that is related to the Mollie module.

**Closed by Marvin-Magmodules** 2022-11-14 12:56 UTC
