### ISSUE TITLE
Orders which are paid have the status 'Cancel' in Magento

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#468] opened 2021-12-03 18:44 UTC
**Describe the bug**
A customer places an order and it's paid via Mollie.
In the Mollie dashboard I see 2 payment attemps, 1 is expired and another one is succeeded, but the order status in Magento is cancelled.

Printscreens Mollie Dashboard:
![image](https://user-images.githubusercontent.com/17478858/144655647-82cacdba-6c83-48e8-8dce-f95da4ddc992.png)

Magento order status:
![image](https://user-images.githubusercontent.com/17478858/144655719-5facdc36-c71a-4990-af04-4d17512b5fe9.png)

Information about the payment in Magento:
![image](https://user-images.githubusercontent.com/17478858/144655848-f5f4814f-4565-4c62-8ca4-d9cedf662d27.png)

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: v1.30.0

**Expected behavior**
The order shouldn't be cancelled if the payment by the customer succeeded.
Now it's easy to completely overlook this order which leads to unhappy customers/questions from customers

**Comment by Frank-Magmodules** [comment] 2021-12-06 09:07
HI @gerben86 ,   
Thank you for opening this issue, it seems that your Mollie version is outdated and as we can't reproduce this issue in the latest version, I would recommend updating the plugin to the latest [version](https://github.com/mollie/magento2/releases) as that should fix your issue. We are closing this issue now but please feel free to reopen the issue if you have any other comments or questions regarding this issue.

**Closed by Frank-Magmodules** 2021-12-06 09:07 UTC
Labels: question
