### ISSUE TITLE
Not possible to store API key in env.php

### ISSUE THREAD

**Issue by okolya** [mollie/magento2#618] opened 2023-02-27 12:41 UTC
**Describe the bug**
When API key is stored in env.php then validation throw the error after updating configuration

`An API key must start with 'test_' or 'live_' and must be at least 30 characters long`

**Used versions**
- *Magento Version number(eg 2.4.5-p1)*:
- *Open source*:
- *Mollie version number v2.22.0*:

**To Reproduce**
1. add API key with CLI and store it in env.php `bin/magento config:set --lock-env payment/mollie_general/apikey_test test_XXXXXXXXXXXXXXX`
2. value is encrypted in env.php and does not contains `test_` string anymore
3. update Magento config using CLI command `bin/magento app:conf:import`
4. See error `An API key must start with 'test_' or 'live_' and must be at least 30 characters long`

**Expected behavior**
It is possible to keep encrypted API key in env.php .

**Comment by Frank-Magmodules** [comment] 2023-02-28 15:36
HI There @okolya , 

Thanks for opening this issue. Are there any more steps involved in this? We tried to reproduce this but on a fresh Magento 2 installation this seems to work fine.

**Comment by norgeindian** [comment] 2023-03-14 13:12
We're facing the exact same issue and actually it should be reproducible exactly like @okolya wrote in my eyes.

**Comment by Frank-Magmodules** [comment] 2023-03-16 11:02
Hello @norgeindian and @okolya, would it be possible for us to review the details with you to ensure that we have the correct information for debugging and, of course, resolving this issue? Your assistance would be greatly appreciated. If you are willing to help, [please contact](https://www.magmodules.eu/support-form.html) us directly so we can proceed debugging this together.

**Comment by Frank-Magmodules** [comment] 2023-04-12 08:33
Hi there @okolya and @norgeindian , 

We wanted to let you know that we have made some changes to the logic in the affected part of the plugin, although we were not able to reproduce the issue directly.

We kindly request that you try out the [latest release](https://github.com/mollie/magento2/releases/tag/v2.24.0) to check if the problem still persists. If you need any further assistance, please don't hesitate to let us know. We look forward to hearing back from you.

**Comment by oneserv-heuser** [comment] 2023-04-19 12:32
Hey, we also have the same problem and we're using the newest version `v2.24.1`. Just updated from `v2.21.1` to it yesterday and since then we have the issue.

**Comment by norgeindian** [comment] 2023-05-03 12:33
I just updated to `2.24.1` and for me, it works since then.

**Comment by Frank-Magmodules** [comment] 2023-05-10 12:47
Hello @oneserv-heuser, I would like to inquire if this issue is still persisting for you. According to @norgeindian, the issue has been resolved with the latest release. Please let me know if the issue is still present so that we can investigate it further or if it has been resolved, we can proceed to close the issue.

**Comment by oneserv-heuser** [comment] 2023-05-15 08:24
Hi @Frank-Magmodules, we just updated to ``2.25.0`` and everything works as intended! Thank you.

**Comment by Frank-Magmodules** [comment] 2023-05-15 08:29
Great, @oneserv-heuser! Thank you for confirming and being patient here. Closing this issue for now.

**Closed by Frank-Magmodules** 2023-05-15 08:29 UTC
Labels: help wanted, Investigating

**Comment by norgeindian** [comment] 2023-05-22 06:41
@oneserv-heuser, we actually had similar issues in the beginning.
But adding the keys again in the admin area and saving the configuration solved it in our case.

**Comment by MarianNapi** [comment] 2023-05-23 11:56
@norgeindian 
> But adding the keys again in the admin area and saving the configuration solved it in our case.

As far as I know this also changes the hashed key in the env.php right? So you would have to update the new hash in every system

**Comment by norgeindian** [comment] 2023-05-24 07:03
Well, as long as you have the stored keys in the `env.php`, you should not be able to adapt anything at all in the admin area, as far as I know.
So what I did was, if I remember correctly, to comment out the keys in the `env.php`, saving them in the admin area, adding the keys again in the file and running `setup:upgrade`. Could you maybe try that process?
