### ISSUE TITLE
Webhook failed with status code 425 (Unordered Collection)  messages in Mollie and duplicate Registered notification about captured amount of XX in Magento

### ISSUE THREAD

**Issue by jamieolney** [mollie/magento2#769] opened 2024-04-10 09:22 UTC
**Describe the bug**
When paying with Apple Pay, webhook failed messages appear in Mollie and duplicate registred notification in Magento appear. 
Seems similar to issue 679 that I opened last year

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5p1
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.36.0

**To Reproduce**
Use Apple pay and checkout as usual

**Expected behavior**
When placed, history should go from Payment of type credit card paid 10 April 2024 at 10:09 to Webhook called successfully, it took 0.6 seconds 10 April 2024 at 10:10
**Actual behavior**
There are one or two Webhook failed with status code 425 (Unordered Collection) messages and an additional Registered notification about captured amount of XX is registered in Magento 2. 

**Screenshots**
![image](https://github.com/mollie/magento2/assets/7457106/fb34f7d2-d10a-4f70-a377-4fb5d261590b)

![image](https://github.com/mollie/magento2/assets/7457106/5ddd7465-7191-4455-a865-4db32ff0327d)

**Additional context**
No issues with version 2.30.1
Using payments API and apple pay direct

**Comment by Frank-Magmodules** [comment] 2024-04-15 06:54
Hi There @jamieolney ,

Thank you for opening this issue. The 425 error is expected with Apple Pay. As Apple Pay goes to paid immediately, the first webhook already comes in before we receive the response from Mollie on creating the transaction. This led to different problems in the past, deciding us to delay the processing of this.

For the multiple “Registered notification about” messages: that is caused by multiple webhook calls that are successfully processed. That only occurs when the response of the webshop on the webhook is too slow. Usually, this can be mitigated by setting `Stores` -> `Configuration` -> `Mollie` -> `Advanced` -> `Process transactions in the queue (experimental)` to `Yes`.

**Comment by Frank-Magmodules** [comment] 2024-04-29 07:16
Hello @simonmaass, Please see my previous comment, also that error has to do with having a response too fast when paying using Apple Pay.

**Comment by Frank-Magmodules** [comment] 2024-05-21 18:11
Hi @simonmaass,
Please let me know if this is now clear for you or if we can close this issue.
Thanks!

**Comment by Frank-Magmodules** [comment] 2024-06-17 10:56
Hi there @simonmaass , can we safely close this issue? Thank you!

**Comment by Frank-Magmodules** [comment] 2024-06-26 09:16
Due to inactivity, I'm closing this issue. 
If you feel it is necessary, please feel free to reopen or comment on the issue.

**Closed by Frank-Magmodules** 2024-06-26 09:16 UTC
Labels: Investigating
