### ISSUE TITLE
Webhook transaction (database) not fail safe

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#151] opened 2019-06-01 09:05 UTC
## Steps to reproduce

1. Place order using Mollie
2. Receive webhook
3. Fail or timeout during webhook
4. Mollie will resend the webhook while the order is in a 'in between state'

## What is the current bug behavior?

If and when the webhook fails it will leave the order in a half way state. This is due to the fact that there is no transaction being used to save the order, invoice, payment and transaction. During the processing of a a capture webhook the order might be saved as much as **6 times!**.

1. To save the additional information `Mollie\Payment\Model\Client\Orders:273`
2. To save the order after invoice creation `Mollie\Payment\Model\Client\Orders::318`
3. To add a status comment `Mollie\Payment\Model\Client\Orders::328`
4. After the order e-mail has been send `Mollie\Payment\Model\Client\Orders::341`
5. After the invoice e-mail has been send `Mollie\Payment\Model\Client\Orders::347`
6. To set the default state `Mollie\Payment\Model\Client\Orders::355`

## What is the expected correct behavior?

If a webhook fails it should not persist or rollback.

## Possible solution

Magento still seems to rely on `\Magento\Framework\DB\Transaction` to do fail save transactions. While this does not align with their ORM vision it seems like the best solution since using a connection transaction might cause other issues like https://github.com/magento/magento2/issues/7597.

In general it's bad practice to save a order that many times since each save will lock the table and might cause problems on high volume webshops.

**Comment by Frank-Magmodules** [comment] 2019-06-05 12:45
Hi @Swahjak ,

Thanks for opening this issue. This piece of code is about the core of this extension, and changing parts of it is something we prefer not to do. That said, if there are serious issues we surely would like to fix them. In your ticket you only describe possible problems, but do you have a clear and reproducible bug? If so, could you provide us with this report so we can investigate this further?

_PS: Innodb does row locking, not table locking. It doesn't takes away the fact that there should only be 1 ->save() call, but it only locks the row._

**Comment by Swahjak** [comment] 2019-06-06 15:43
I would say that saving an order 6 times while it should only be saved once is a pretty serious issue. I understand that you like to be careful, so do I, but shooting down every issue with "we don't like to change code" is not very constructive. Should I contact Mollie directly about these issues and make sure that they know I'm not happy about it? Not to threaten, but I assume the extension is (partially) being build on their budget(?).

I have had issues with this on a heavy load where the database had a hard time keeping up. Not putting that on you, the database also needed a bit more juice. But saving orders 6 times, doing lookup on non-indexed columns wan't helping the case. Try setting a breakpoint half way between the saves and make the webserver timeout.

**Comment by Swahjak** [comment] 2019-06-11 17:08
@Frank-Magmodules further investigation also revealed the following line in the Mollie documentation (not sure if this is correct):
> Our webhook calls time out after 15 seconds. Even if you return a 200 OK HTTP status after 16 seconds, we will mark the webhook call as failed and try again later.

Something i noticed as well is that the `\Mollie\Payment\Model\Client\Orders` class returns a variable `$msg` so does `Mollie\Payment\Model\Mollie` but the message is actually only handled by the `Success` controller, not by the `Webhook` controller. As far as I can see the webhook will always succeed unless the timeout of 15 seconds is reached since any error is caught in `Mollie\Payment\Controller\Checkout\Webhook` on line 80.  Is this observation correct?

**Comment by Swahjak** [comment] 2019-06-11 20:39
After even further reading the choice to always return a `200 OK` status might be related to
> To not leak any information to malicious third parties, it is recommended to return a 200 OK response even if the ID is not known to your system.
Although that woud only explain why invalid credentials or transaction id's lead to a `200 OK` status. As soon as the credentials and transaction id's are processed and validated it could be assumed that we have a safe environment.

**Comment by Frank-Magmodules** [comment] 2019-06-12 14:41
HI @Swahjak , thanks for your messages, i'm just letting you know that we are investigating this as well and we will update you once we have a substantive update on this.

**Comment by Frank-Magmodules** [comment] 2019-06-14 09:28
Hi @Swahjak ,

We have made some changes in this process, but as this is a critical part in the extension the testing process can take some time. We will update this issue once done and succeeded. 

> As far as I can see the webhook will always succeed unless the timeout of 15 seconds is reached since any error is caught in Mollie\Payment\Controller\Checkout\Webhook on line 80. Is this observation correct?

No, since 1.6.0 it can also return a 503 if there is an exception, see: https://github.com/mollie/magento2/blob/master/Controller/Checkout/Webhook.php#L83

> Something i noticed as well is that the \Mollie\Payment\Model\Client\Orders class returns a variable $msg so does Mollie\Payment\Model\Mollie but the message is actually only handled by the Success controller, not by the Webhook controller.

This will pass a success true or false to the Success controller to redirect to customer to the checkout succes page or to the cart for a retry. This is based on the data from the request, so there is no logic to apply this to the Webhook controller.

**Comment by Swahjak** [comment] 2019-06-14 10:28
Hi @Frank-Magmodules,

Thank you for your response. 
> No, since 1.6.0 it can also return a 503 if there is an exception, see: 

I'm sorry I missed that, at the time of writing we had version 1.5.2 running.
> This will pass a success true or false to the Success controller to redirect to customer to the checkout succes page or to the cart for a retry. This is based on the data from the request, so there is no logic to apply this to the Webhook controller.

Ok, knowing it will return a 503 since 1.6.0 it actually makes sense to rely on throwables to catch errors at the lowest level.

> We have made some changes in this process

Is the related code available somewhere?

**Comment by Marvin-Magmodules** [comment] 2019-06-18 17:58
Hi @Swahjak 

> Is the related code available somewhere?

Yes see [PR 159](https://github.com/mollie/magento2/pull/159). The processTransaction function has been optimized by reducing the order saves.

**Comment by Swahjak** [comment] 2019-06-19 05:22
@Marvin-Magmodules @michielgerritsen thanks for your efforts. Since this still has to be tested, is there any chance the order saves could be wrapped in a database transaction? Less saves makes it more fault tolerant, but there is still the chance of 'failure' between saves. A simple transaction could remove (reduce) this riks.

**Comment by Marvin-Magmodules** [comment] 2019-06-21 14:15
@Swahjak sure, we have just added this to the PR, see: https://github.com/mollie/magento2/pull/159/commits/58b257f0ee2d9e44196eb3cd1085754c8da32732

**Comment by Frank-Magmodules** [comment] 2019-06-24 12:08
Issue has been resolved and merged into [v1.6.2](https://github.com/mollie/magento2/releases/tag/v1.6.2) release. Closing this issue now. Feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2019-06-24 12:08 UTC

**Comment by Swahjak** [comment] 2019-07-17 14:13
Just a heads up, I think the transaction wrapping might be causing `_commit_after` events not to be fired. As stated before magento/magento2#7597 seems to be the cause of this. I'm not a 100% sure yet, but this seems to be the case for us. Never a dull moment with Magento 2.
