### ISSUE TITLE
Order Item qty_invoiced does not update when use Apple pay method.

### ISSUE THREAD

**Issue by htcmage** [mollie/magento2#666] opened 2023-07-26 11:27 UTC
I'm making a feature to create invoice order automatically in Magento but facing this issue with Mollie/Apple pay. That is the qty_invoiced of order item was not updated correctly. It leads the issue function \Magento\Sales\Model\Order::canInvoice cannot return correct value and I can create multiple invoices for one order even all items have been invoiced.

**Used versions**
- *Magento Version number*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Enterprise (Cloud)
- *Mollie version number (Check configuration)*: 2.28.0

**To Reproduce**
1. Add one simple product to cart
2. Go to checkout
2. Checkout with Apple Pay
3. Order success

**Expected behavior**
The order is created successfully. 
The invoice is created successfully. 
The column sales_order_item.qty_invoiced is updated is 1 (It means the item has been invoiced fully)

**Actual behavior**
The column sales_order_item.qty_invoiced is updated is 0 (It means the item has not been invoiced fully)

**Comment by Frank-Magmodules** [comment] 2023-07-27 11:09
Hello @htcmage, we appreciate you raising this issue, and it appears to be valid. Our team is currently conducting a thorough investigation into the root cause of the problem and, of course, working on finding a suitable solution. Thank you for bringing this to our attention.

**Comment by nileshrvs** [comment] 2023-08-07 07:37
Hi team

we had same issue with Magento v2.4.5-p1 with Mollie Apple pay v2.29.1.
Invoice were created for the order but it still show Due Amount in order.

**Comment by Frank-Magmodules** [comment] 2023-08-08 18:14
Hello @nileshrvs and @htcmage,
I'm happy to inform you that we have successfully resolved this issue in our [most recent release](https://github.com/mollie/magento2/releases/tag/v2.30.0). Your detailed issue report greatly aided us in reproducing and addressing the problem. While we are closing this matter at present, please know that you are welcome to reopen it should the need arise. Thank you once again for bringing this to our attention.

**Closed by Frank-Magmodules** 2023-08-08 18:14 UTC
Labels: bug, Reproduced & ready for release
