### ISSUE TITLE
Backend payment link redirects sometimes to root site

### ISSUE THREAD

**Issue by dragonfly4** [mollie/magento2#808] opened 2024-08-21 10:41 UTC
We have issues with the backend payment link when an admin creates an order. I cannot simulate it which is annoying.

Version 2.4.0 with Magento 2.4.6-p6 community. PHP 8.2

The link goes to
`https://ourwebsite.be/nl/mollie/checkout/paymentlink/order/MDozOnIxUEdkNGRRTTRjcVFIT015dFptK3RJQlp5NkhUQ0daZ1JoMGxxxxxxx/`

which sometimes redirects to the root folder without message. Sometimes it redirects to the Mollie payment page 'https://www.mollie.com/checkout/select-method/QpgMxxxxxxx'

![Mollie_backend](https://github.com/user-attachments/assets/b32b3787-2686-4bf8-bae4-9290bb7794d3)
            
The shop is active under pub  folder so nothing special. It is a multistore set-up.

Which file in this module is the best to start debugging this redirect please? That way I can hopefully find the root issue as nothing is logged.

**Comment by dragonfly4** [comment] 2024-08-21 10:41
@Frank-Magmodules Thx for looking into this. I have opened a new issue. (https://github.com/mollie/magento2/issues/806#issuecomment-2296360403)

**Comment by dragonfly4** [comment] 2024-08-22 12:57
As I am unable to reproduce this issue myself I tried to recreate an order. It gave me an out-of-stock warning so I guess this problem might be related to https://github.com/mollie/magento2/issues/795 as that mentions a stock check.

I will update from 2.40.0 to 2.40.1 to see if that helps. (maintenance window is weekend)

**Comment by Frank-Magmodules** [comment] 2024-08-22 13:10
Thanks @dragonfly4, just let me know—I'm happy to assist. Also, don't hesitate to [reach out to us directly](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu).

**Comment by Frank-Magmodules** [comment] 2024-09-10 09:03
Hi @dragonfly4,  we’ve just released a new version of the Mollie plugin, [2.41.0](https://github.com/mollie/magento2/releases/tag/v2.41.0), which includes an adjustment to the Paymentlink. Since neither of us could reproduce the issue anymore, I’m closing this for now. However, feel free to reopen or comment if you encounter the issue again.

**Closed by Frank-Magmodules** 2024-09-10 09:03 UTC
Labels: Investigating
