### ISSUE TITLE
Mollie API: Error executing API call (422: Unprocessable Entity): Cannot create a shipment. 

### ISSUE THREAD

**Issue by Goeny** [mollie/magento2#250] opened 2020-04-28 10:07 UTC
Since we updated to 1.12.1 the Payment link works as expected. However we experience the following issue since using this. (This could be an issue from before 1.12.1 but we only started using the payment link since now)

When creating an order with a payment link the order is sent as expected.
The customer decides to pay using regular bank payment without using the mollie link.
We can create an invoice and in Magento the order is payed. 
However... The Mollie Payment status remains "Created"
We cannot create shipment (And thus we cannot complete the order)

Error:
`Mollie API: Error executing API call (422: Unprocessable Entity): Cannot create a shipment. No lines can be shipped.. Documentation: https://docs.mollie.com/reference/v2/shipments-api/create-shipment`

How can we get this fixed?
We have multiple orders which cannot be completed.

**Comment by Frank-Magmodules** [comment] 2020-04-29 11:20
Hi @Goeny ,

Seems we can't reproduce this based on the information given. To do reproduce I need the exact steps on how to reproduce it together with the specified order details and logfile. Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange;

- Mollie Logfile from /var/log/mollie.log
- (Temporary) Magento Back-end details
- Order Details

In that way, we can help you out with this.
Thanks,

Frank

**Comment by Goeny** [comment] 2020-04-30 09:21
@Frank-Magmodules ,

Sent all information through the contact form yesterday evening.

**Comment by Frank-Magmodules** [comment] 2020-05-01 14:01
@Goeny, Again, thank you for opening this issue.
We have reproduced this issue and create a fix so you can manually mark the PaymentLink order as paid so you can ship it.
This solution is currently being tested so that it can be included in the release early next week, we will update this issue once the release is there.

Frank

**Comment by Frank-Magmodules** [comment] 2020-05-07 09:18
Hi @Goeny, thanks again for the detailed issue report. The issue has been resolved in the [v1.13.0](https://github.com/mollie/magento2/releases/tag/v1.13.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-05-07 09:18 UTC

**Comment by Goeny** [comment] 2020-05-07 10:53
@Frank-Magmodules 

Thank you for the update.

I just updated to 1.13.0 and unfortunately the issue persist.
I suppose it has to do with the absence of the "manuallly paid" button. It is still not there. (Or i must overlooked something.
