### ISSUE TITLE
Vouchers stays available

### ISSUE THREAD

**Issue by BrentRobert** [mollie/magento2#465] opened 2021-11-29 15:28 UTC
**Describe the bug**
I add two products to my cart.
One contains my custom attribute with value 'eco' the other with the value 'none'.
I'm able to pay the whole order with echocheques, while this is legally not allowed for half of my cart.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3-p1
- *Open source/Enterprise/B2b*: Enterprise
- *Mollie version number (Check configuration)*: v2.3.0

**To Reproduce**
1. Add a product that's not an eco product
2. Add a product that is an eco product

**Expected behavior**
I expect the voucher method to NOT be available, as not the full order can be paid with ecocheques

**Actual behavior**
I can pay the full order with ecocheques, while one of the items is not legally allowed to.

**Comment by Frank-Magmodules** [comment] 2021-12-17 09:58
HI @BrentRobert ,

Thank you for opening this issue and sorry for my late response on this, we've tried to reproduce the issue that you describe but we can't reproduce this issue directly. Can you please share the exact steps or the expected behavior with us through our [support form](https://www.magmodules.eu/support-form.html) so we can take a look with you?

**Comment by Frank-Magmodules** [comment] 2022-01-07 12:19
HI @BrentRobert ,

Due to the lack of information and we can't reproduce this issue, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2022-01-07 12:19 UTC
Labels: Investigating
