### ISSUE TITLE
Creditmemo's created cannot be refunded if same orderline is refunded in separate creditmemo's.

### ISSUE THREAD

**Issue by kennethbonte** [mollie/magento2#456] opened 2021-11-04 12:47 UTC
**Describe the bug**
Creditmemo's created cannot be refunded if same order line is refunded in separate creditmemo's.

**Used versions**
- *Magento Version number 2.4.3*:
- *Open source/Enterprise/B2b*:
- *Mollie version 2.2.0*:

**To Reproduce**
1. Create an order with qty >= 2 for same product with Mollie payment
2. Create creditmemo by only returning 1 of several products from order line, choose refund online
3. Create creditmemo by returning other products from order line, choose refund online
4. See error "Error executing API call (409: Conflict): A duplicate refund has been detected. Documentation: https://docs.mollie.com/overview/handling-errors"

**Expected behavior**
Creditmemo's can be created and refunded when splitting creditmemo's for same orderline.

**Actual behavior**
Error when trying to refund same orderline
Error executing API call (409: Conflict): A duplicate refund has been detected. Documentation: https://docs.mollie.com/overview/handling-errors [] []

**Comment by Frank-Magmodules** [comment] 2021-11-08 10:59
HI @kennethbonte ,

Thank you for opening this issue. It seems that we can't reproduce this issue from our side, can you please fill in our [support form](https://www.magmodules.eu/support-form.html) with (preferably staging/development) details of the environment so we can take a look with you on this issue?

**Comment by Frank-Magmodules** [comment] 2021-11-24 14:44
HI @kennethbonte ,

We did not receive any information about this issue yet.  
Can you please share an update on this? As we can't reproduce this from ourselves.

**Comment by Frank-Magmodules** [comment] 2021-12-06 09:22
HI @kennethbonte ,

We didn't receive any response on this issue anymore, therefore, we will close this issue for now. Please feel free to reopen the issue or contact us directly through our [contact form](https://www.magmodules.eu/support-form.html) so we can investigate this issue further with you.

**Closed by Frank-Magmodules** 2021-12-06 09:22 UTC
Labels: Investigating
