### ISSUE TITLE
[SETUP] PHP Fatal error on "Mollie\\Payment\\Model\\Methods\\ApplePay" after updating to v.2.34.0

### ISSUE THREAD

**Issue by RobbeSaelens** [mollie/magento2#746] opened 2024-02-21 14:49 UTC
**Describe the bug**
After updating the module with composer to v.2.34.0 i get this error message on checkout in the frontend:
`PHP Fatal error:  Declaration of Mollie\\Payment\\Model\\Methods\\ApplePay\\Interceptor::refund(Magento\\Payment\\Model\\InfoInterface $payment, $amount): Mollie\\Payment\\Model\\Methods\\ApplePay must be compatible with Mollie\\Payment\\Model\\Mollie::refund(Magento\\Payment\\Model\\InfoInterface $payment, $amount): Mollie\\Payment\\Model\\Mollie`

**Used versions**
-  *Magento Version number*: v2.3.3
- *Mollie version number*: v.2.34.0

**To Reproduce**
After installing the latest mollie version with composer and going to my checkout page on the frontend

**Comment by Frank-Magmodules** [comment] 2024-02-22 07:45
HI There @RobbeSaelens , Goodmorning,

Thank you for opening this issue. This error is caused by the fact that you need to run `setup:di:compile` after you update an extension. To prevent such errors in the future, we strongly advise implementing a structured deployment procedure. While setting this up initially might be challenging, we recommend utilizing Deployer for this purpose:
https://deployer.org/docs/7.x/recipe/magento2

Feel free to reach out if you need additional assistance with the Mollie plugin.

**Comment by Frank-Magmodules** [comment] 2024-02-26 15:29
Hello @RobbeSaelens! Did our comment help you address this issue?

**Comment by Frank-Magmodules** [comment] 2024-02-26 20:44
Perfect, thanks @RobbeSaelens , I'm closing this issue now. Have a good evening!

**Closed by Frank-Magmodules** 2024-02-26 20:44 UTC
Labels: Question / Issue, Investigating
