### ISSUE TITLE
Pending Payment that has already been cancelled.

### ISSUE THREAD

**Issue by Margero** [mollie/magento2#240] opened 2020-04-04 09:21 UTC
I have a Klarna order that has not been cancelled properly:
Payment Status is: Pending payment

When I try to cancel the order I get the following error message:
Error executing API call (400: Bad Request): The order cannot be canceled from state: canceled. Documentation: https://docs.mollie.com/guides/handling-errors

Because of this the systeem keeps trying to cancel the order automatically and adding the products back to products qty without the order being cancelled. This created a infinite loop adding 1000 of products back to stock.
![Pending Payment Klarna](https://user-images.githubusercontent.com/31563367/78423388-44215b80-7666-11ea-9395-97137f99b45f.jpg)

**Comment by Margero** [comment] 2020-04-04 09:26
I think this can be solved with:

If status is (already) cancelled than return this status. 
(I am not a developer so I would now know how to write this but I have some knowledge of coding structure)

**Comment by Frank-Magmodules** [comment] 2020-04-07 18:19
Hi @Margero ,

Thank you for opening this issue. Can you please share the steps to reproduce this and together with the used Magento and Mollie version? As I can't reproduce this on the latest version of the extension.
Was the payment canceled in the Mollie dashboard perhaps? 

Frank

**Comment by Margero** [comment] 2020-04-12 09:11
Hi,

I don't know how the order was cancelled in Mollie. I did not cancel the order so I suspect this was cancelled automatically after xxx days. But this cancellation was not registered in my Magento and when Magento was trying to cancel the order this the above problem occurred. I had an order with status "pending payment" and cancellation was impossible because mollie would give error message. So Magento kept trying to cancel the order and adding the products every time back to stock.

**Comment by Frank-Magmodules** [comment] 2020-04-14 08:48
Hi @Margero ,

Seems we can't reproduce this here on different Magento versions but please share us the exact steps on how to reproduce this issue. Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange the steps, log files and login details so we can check and fix this issue?

**Comment by Frank-Magmodules** [comment] 2020-04-16 07:20
Hi @Margero 

The issue has been resolved in the [v1.12.2](https://github.com/mollie/magento2/releases/tag/v1.12.2) release where we do not try to cancel the order in Mollie when it is already canceled in Mollie. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Closed by Frank-Magmodules** 2020-04-16 07:20 UTC

**Comment by Margero** [comment] 2020-04-16 07:33
Hi,

Thank you for the update. But did you also include to give this status back to magento?
If order is already cancelled in mollie than cancel the order in magento?

**Comment by Frank-Magmodules** [comment] 2020-04-16 13:00
Hi @Margero, 

Yes, it will be canceled by the webhook if status changed, or can be canceled by using [Cancel] in the order.
