### ISSUE TITLE
Duplicated shipments

### ISSUE THREAD

**Issue by visualwebs** [mollie/magento2#358] opened 2021-02-15 19:00 UTC
I want to share this issue to see if anyone got same case

We use an ERP system from BoostMyshop that creates shipments in a custom step, called Order preparation. Managers selects the order and click on "pack". This generate the shipment.
In that instant, Mollie creates an entry in the order comments history.

"Registered notification about captured amount of €XXXX. Transaction ID: "ord_*****""

Sometimes this happens. For example shipment is created a 12:00:00, Mollie calls the "sales_order_shipment_save_before" event and the shipment is created again at 12:00:01, 2 times. So shipment appears duplicated.

I see in the Mollie code that the order object saving, is called in the middle of the process of creating the shipment

`$this->orderRepository->save($order);`

Is possible that this call is generating a sort of loop and saving order 2 times so is the reason of duplicated shipments? The order and shipping is saved in this way in the ERP code.

```
$transaction = $this->_objectManager->create(
            \Magento\Framework\DB\Transaction::class
        );
        $transaction->addObject(
            $shipment
        )->addObject(
            $shipment->getOrder()
        )->save();
```

**Comment by Frank-Magmodules** [comment] 2021-02-22 13:49
Hello @visualwebs,

Thanks for opening this issue. This specific issue doesn't ring a bell with us. What we have seen in the past is that some (external) systems first create a shipment, and then later add details like items and totals. Could this be the case?

About the `sales_order_shipment_save_before` event: Mollie has a listener at this event. 
If this is called at the wrong moment it could give some unexpected results.

**Comment by Frank-Magmodules** [comment] 2021-03-08 12:39
Hi @visualwebs ,

Do you have any updates on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by visualwebs** [comment] 2021-03-15 12:57
Yes. I bypassed the Mollie observer and after several weeks I can say the problem was resolved.
So anything happens on the Mollie side when other modules are creating the shipment in the way as described here.

**Comment by Frank-Magmodules** [comment] 2021-03-22 09:21
Hello @visualwebs,

Good to hear that this issue is resolved for you. We are still unsure why this issue happened to you in the first place, but we think that this happens due to the combination with a third-party module as we are not able to reproduce this issue on our end. 

For this reason, we are closing this issue now but please feel free to contact us [directly](https://www.magmodules.eu/support-form.html) with more details about this environment with this third party module so we can help you debug, locate and fix the issue if it occurs again.

**Closed by Frank-Magmodules** 2021-03-22 09:21 UTC
Labels: Investigating
